"""
t1_pet_data.py - TOKEN QUEST: 토큰펫 콘텐츠 테이블

게임 로직(t1_pet.py)과 화면(t1_pet_ui.py)에서 공통으로 쓰는 "데이터"만 모아 둔 파일.
숫자 밸런스는 대부분 여기서 조절한다.
"""

GAME_TITLE = "TOKEN QUEST"
SAVE_VERSION = 4   # v3: 세대/명예의 전당, 성격, 훈육, 퀘스트 로그(opencode todo), 주간 레이드 · v4: 메인 스토리(주간 챕터)

# ============================================================== 표정 (항상 3칸)
FACES = {
    "normal": "o_o", "blink": "-_-", "happy": "^_^", "joy": "^o^", "love": "*_*", "proud": "^v^",
    "hungry": "._.", "sad": "T_T", "sleepy": "=_=", "sleep": "u_u", "sick": "~_~", "burnout": "x_x",
    "angry": ">_<", "anxious": "o_O", "eat1": "^o^", "eat2": "^-^", "battle": ">_>", "hurt": ">.<",
    "bored": "-_-", "dizzy": "@_@", "wink": "^_~",
}

# ============================================================== 진화 형태
# mult: (hp, atk, def, int, spd, luk) 배율 / ideal: 적정 몸무게(KB) / ult: 궁극기 스킬 id
# art: 2프레임 x 4줄, 폭 11칸. {f} 자리에 3칸 표정이 들어간다.
STAGES = ["알", "유아기", "유년기", "청소년기", "성체", "전설"]

FORMS = {
    "egg": dict(
        name="알", stage=0, color="#D4D6D8", mult=(1, 1, 1, 1, 1, 1), ult=None, ideal=0.5,
        desc="무언가 꿈틀거린다. 첫 응답이 도착하면 깨어날지도?",
        art=[[r"    ___    ", r"   /   \   ", r"  | egg |  ", r"   \___/   "],
             [r"    ___    ", r"   / . \   ", r"  | egg |  ", r"   \___/   "]],
        crack=[r"    _/\    ", r"   /  .\   ", r"  | e g |  ", r"   \___/   "]),
    "bit": dict(
        name="비트", stage=1, color="#B8CEE0", mult=(1, 1, 1, 1, 1, 1), ult=None, ideal=1.0,
        desc="0과 1 사이에서 태어난 아기 토큰펫. 아직 말랑말랑하다.",
        art=[[r"           ", r"   .---.   ", r"  ( {f} )  ", r"   `---'   "],
             [r"           ", r"   .---.   ", r"  ( {f} )  ", r"   '---`   "]]),
    "byte": dict(
        name="바이트", stage=2, color="#95D85A", mult=(1.02, 1.02, 1.02, 1.02, 1.02, 1.02), ult=None, ideal=2.0,
        desc="8비트가 모여 한 바이트. 더듬이로 와이파이를 잡는다.",
        art=[[r"    \ /    ", r"   .---.   ", r"  ( {f} )  ", r"   /| |\   "],
             [r"    | |    ", r"   .---.   ", r"  ( {f} )  ", r"   \| |/   "]]),
    "junior": dict(
        name="주니어 개발자", stage=3, color="#75A1C7", mult=(1.05, 1.05, 1.05, 1.08, 1.05, 1.05), ult=None, ideal=4.0,
        desc="헤드폰을 끼고 열정이 넘친다. PR 리뷰 댓글에 상처받기 쉬움.",
        art=[[r"   _____   ", r"  @({f})@  ", r"  /|=#=|\  ", r"   _| |_   "],
             [r"   _____   ", r"  @({f})@  ", r"  \|=#=|/  ", r"   _| |_   "]]),
    "kiddie": dict(
        name="스크립트 키디", stage=3, color="#A5AAAE", mult=(1.0, 1.12, 0.95, 0.95, 1.1, 1.1), ult=None, ideal=4.0,
        desc="모자를 거꾸로 쓰고 복붙으로 세상을 해킹(?)한다. 돌봄이 조금 부족했다.",
        art=[[r"   ___/>   ", r"  ( {f} )  ", r"  /|$_ |\  ", r"   _| |_   "],
             [r"   ___/>   ", r"  ( {f} )  ", r"  \|$_ |/  ", r"   _| |_   "]]),
    "tenx": dict(
        name="10x 개발자", stage=4, color="#6ABA23", mult=(1.1, 1.3, 0.95, 1.1, 1.2, 1.05), ult="tenx", ideal=8.0,
        desc="전설 속의 그 존재. 남들 열 명 몫을 한다고 본인이 말한다.",
        art=[[r" *  _^_  * ", r"   ({f})   ", r"  -|10x|-  ", r"   /   \   "],
             [r"  * _^_ *  ", r"   ({f})   ", r"  =|10x|=  ", r"   \   /   "]]),
    "hunter": dict(
        name="버그 헌터", stage=4, color="#95D85A", mult=(1.1, 1.15, 1.05, 1.05, 1.2, 1.35), ult="breakpoint", ideal=8.0,
        desc="잠자리채 하나로 프로덕션 버그를 사냥한다. 방이 늘 깨끗하다.",
        art=[[r"   ___   @ ", r"  ({f})  / ", r"  /|###|/  ", r"   /   \   "],
             [r"   ___  @  ", r"  ({f}) /  ", r"  /|###|   ", r"   /   \   "]]),
    "architect": dict(
        name="시니어 아키텍트", stage=4, color="#75A1C7", mult=(1.15, 1.05, 1.25, 1.35, 0.95, 1.05), ult="microservice", ideal=9.0,
        desc="화이트보드 앞에서 박스와 화살표로 세상을 설명한다. plan 모드를 좋아한다.",
        art=[[r"   _____   ", r"  |[{f}]|  ", r"  /|\_/|\  ", r"   |___|  #"],
             [r"   _____   ", r"  |[{f}]|  ", r"  \|\_/|/  ", r"   |___| # "]]),
    "zombie": dict(
        name="야근 좀비", stage=4, color="#81888D", mult=(1.4, 1.15, 1.0, 0.9, 0.9, 0.85), ult="allnighter", ideal=10.0,
        desc="다크서클이 턱까지 내려왔다. 토큰은 많이 먹었는데 돌봄을 못 받았다.",
        art=[[r"   ,,,,,   ", r"  ({f})~   ", r" __/| |\_c ", r"   /  \    "],
             [r"   ,,,,,   ", r"  ({f})~~  ", r" __/| |\_c ", r"    \  /   "]]),
    "monk": dict(
        name="코드 몽크", stage=4, color="#B8CEE0", mult=(1.15, 1.0, 1.1, 1.3, 1.05, 1.2), ult="meditate", ideal=7.0,
        desc="마음이 평온하면 컴파일 에러도 평온하다. 놀아주면 놀아줄수록 깨달음을 얻었다.",
        art=[[r"    (_)    ", r"   ({f})   ", r"  /(___)\  ", r"   _/ \_   "],
             [r"    ( )    ", r"   ({f})   ", r"  \(___)/  ", r"   _/ \_   "]]),
    "fullstack": dict(
        name="풀스택 드루이드", stage=4, color="#C0E79D", mult=(1.15, 1.15, 1.15, 1.15, 1.1, 1.1), ult="fullstack", ideal=8.0,
        desc="프론트, 백엔드, 인프라, 화분 물주기까지 전부 한다. 균형 잡힌 돌봄의 결과.",
        art=[[r"  ~\|/~    ", r"   ({f})   ", r"  [=|=|=]  ", r"   /   \   "],
             [r"   ~\|/~   ", r"   ({f})   ", r"  [=|=|=]  ", r"   \   /   "]]),
    "singularity": dict(
        name="싱귤래리티", stage=5, color="#6ABA23", mult=(1.4, 1.4, 1.35, 1.5, 1.3, 1.3), ult="singularity", ideal=12.0,
        desc="토큰을 너무 많이 먹어 특이점에 도달했다. 가끔 주인보다 코드를 잘 짠다.",
        art=[[r"  .*'''*.  ", r" ( ({f}) ) ", r"  '*...*'  ", r"    /|\    "],
             [r"  *'''*'.  ", r" ) ({f}) ( ", r"  .*...*.  ", r"    \|/    "]]),
    # 비밀 전설: 여러 세대에 걸쳐 성체 4종 이상을 만나 본 가문에서만 나타난다
    "maintainer": dict(
        name="오픈소스 메인테이너", stage=5, color="#F2F2F3", mult=(1.35, 1.3, 1.45, 1.55, 1.25, 1.4), ult="lgtm", ideal=10.0,
        desc="수천 개의 이슈와 PR을 묵묵히 처리해 온 전설. 여러 세대의 경험이 한 몸에 모였다.",
        art=[[r"  _[LGTM]_ ", r"  ( {f} )  ", r" <|  #  |> ", r"   _/ \_   "],
             [r"  _[LGTM]_ ", r"  ( {f} )  ", r" >|  #  |< ", r"   _/ \_   "]]),
}
ADULT_FORMS = ["tenx", "hunter", "architect", "zombie", "monk", "fullstack"]
LEGEND_FORMS = ["singularity", "maintainer"]
# 진화 도감 순서 (세대를 거치며 모은다)
FORM_ORDER = ["egg", "bit", "byte", "junior", "kiddie"] + ADULT_FORMS + LEGEND_FORMS

# 진화 조건 (엔진이 검사, 도감/프로필에 힌트로 표시)
#   age: 부화 후 경과 분
EVOLVE_RULES = {
    "egg": dict(lvl=1, age=3, hint="부화: 3분 경과 + 첫 응답 도착 (또는 10분 경과)"),
    "bit": dict(lvl=3, age=20, hint="진화: Lv.3 + 부화 후 20분"),
    "byte": dict(lvl=8, age=120, hint="진화: Lv.8 + 부화 후 2시간 (돌봄+훈육이 좋으면 주니어 / 아니면 스크립트 키디)"),
    "junior": dict(lvl=16, age=720, hint="진화: Lv.16 + 부화 후 12시간 (키운 방식·성격·훈육에 따라 6갈래)"),
    "kiddie": dict(lvl=16, age=720, hint="진화: Lv.16 + 부화 후 12시간 (키운 방식·성격·훈육에 따라 6갈래)"),
    "adult": dict(lvl=35, age=7200, hint="전설: Lv.35 + 클라우드 성층권 보스 격파 + 돌봄 75↑ + 5일"),
}
SECRET_HINT = "??? : 여러 세대에 걸쳐 성체를 4종 이상 만난 가문의 성체가 전설 조건을 채우면…"

# ============================================================== 성격 (부화할 때 정해짐)
# 효과 키: energy_decay / mood_decay / full_decay / bug_rate (배율), exp (+비율), spd (+비율), food_mood (배율),
#          dirty_mood (배율), play (+비율), boss_atk (+비율), night_energy / morning_energy (배율)
#   adult: 성체 진화 점수 가산 (키운 방식에 성격이 살짝 섞인다)
PERSONALITIES = {
    "diligent": dict(name="부지런함", desc="체력이 덜 닳고 경험치 +5%. 할 일 목록을 좋아한다.",
                     energy_decay=0.9, exp=0.05, adult={"architect": 0.12},
                     lines=["오늘 할 일 목록 만들어 뒀어요!", "커밋은 작게, 자주! 제 신조예요", "벌써 끝났어요? 저 던전 한 바퀴 더 돌래요!"]),
    "laidback": dict(name="느긋함", desc="기분이 천천히 떨어진다. 대신 조금 느리다.",
                     mood_decay=0.85, spd=-0.05, adult={"monk": 0.12},
                     lines=["천천히 해도 돼요~ 배포는 도망 안 가요", "커피 한 잔 하고 할까요…", "급할수록 git stash~"]),
    "foodie": dict(name="먹보", desc="배가 빨리 꺼지지만 밥 먹을 때 기분이 크게 오른다.",
                   full_decay=1.15, food_mood=1.6, adult={"zombie": 0.06, "fullstack": 0.06},
                   lines=["밥 먹은 지 5분 됐는데 배고파요", "토큰은 간식이고 김밥은 밥이에요", "치킨… 치킨 냄새가 나요…"]),
    "tidy": dict(name="깔끔함", desc="버그가 20% 덜 생긴다. 대신 방이 더러우면 기분이 확 나빠진다.",
                 bug_rate=0.8, dirty_mood=1.4, adult={"hunter": 0.14},
                 lines=["린트 경고 0개! 기분 좋아요", "들여쓰기가 삐뚤어진 걸 못 참아요", "방 정리 좀 할게요… 앗 버그다!"]),
    "playful": dict(name="장난꾸러기", desc="놀이 보상 +30%. 대신 심심함을 잘 타고 떼를 자주 쓴다.",
                    play=0.3, mood_decay=1.1, tantrum=1.6, adult={"monk": 0.12},
                    lines=["놀아줘요! 버그 잡기 한 판!", "몰래 주석에 이모티콘 넣어뒀어요 ^_^", "숨바꼭질해요! 저 node_modules에 숨을게요"]),
    "brave": dict(name="용감함", desc="보스 앞에서 공격력 +8%. 가끔 무모하다.",
                  boss_atk=0.08, adult={"tenx": 0.14},
                  lines=["보스 나와라! 다 덤벼!", "429 드래곤 따위 하나도 안 무서워요", "프로덕션에서 테스트해도… 아 이건 아니다"]),
    "nightowl": dict(name="올빼미", desc="밤(22~4시)엔 체력이 덜 닳고, 아침(6~10시)엔 비몽사몽.",
                     night_energy=0.7, morning_energy=1.25, adult={"zombie": 0.1, "architect": 0.04},
                     lines=["밤이 되니까 집중이 잘 돼요!", "아침… 아침은 너무 밝아요…", "새벽 커밋의 맛을 알아버렸어요"]),
}

# ============================================================== 세대 (은퇴 → 명예의 전당 → 새 알)
RETIRE_RULE = dict(stage=4, lvl=25, days=3)     # 성체 + Lv.25 + 부화 3일 (전설은 언제든)
FAMILY = dict(exp_per_gen=0.05, gold_per_gen=0.03, cap_gen=10)   # 은퇴한 선대 1명당 경험치 +5%, 골드 +3% (최대 10대)
EPITAPHS = {
    "tenx": "열 명 몫을 했다고 본인이 말했다. 아무도 반박하지 못했다.",
    "hunter": "그가 지나간 자리에는 버그 한 마리 남지 않았다.",
    "architect": "화이트보드에 그린 박스와 화살표가 아직도 벽에 남아 있다.",
    "zombie": "야근을 사랑했고, 야근도 그를 사랑했다. 이제는 푹 쉬기를.",
    "monk": "마음이 평온하니 컴파일 에러도 평온했다.",
    "fullstack": "프론트도, 백엔드도, 화분 물주기도 다 했다.",
    "singularity": "특이점에 도달해 우리가 모르는 곳으로 커밋했다.",
    "maintainer": "수만 개의 PR에 LGTM을 남기고 전설이 되었다.",
    "_": "주인님과 함께한 모든 토큰이 소중했다.",
}

# ============================================================== 스킬
# kind: dmg / heal / buff / special
SKILLS = {
    "slash": dict(name="리팩터링 슬래시", mp=5, lvl=1, kind="dmg", power=2.1, desc="스파게티를 썰어버리는 기본기. 공격력 x2.1"),
    "duck": dict(name="러버덕 디버깅", mp=6, lvl=3, kind="heal", power=0.30, desc="오리에게 설명하다 보면 낫는다. HP 30% 회복 + 상태이상 해제"),
    "tdd": dict(name="TDD 방패", mp=7, lvl=5, kind="buff", buff="def_up", turns=3, desc="테스트가 먼저 맞아준다. 3턴간 방어력 x1.6"),
    "revert": dict(name="git revert", mp=8, lvl=8, kind="special", desc="직전에 받은 피해를 되돌린다 (x1.5 회복)"),
    "so": dict(name="스택오버플로우 검색", mp=6, lvl=11, kind="special", desc="무엇이 나올지 모른다. 정답일 수도, '중복 질문'일 수도"),
    "hotfix": dict(name="핫픽스", mp=12, lvl=14, kind="dmg", power=3.4, recoil=0.2, desc="강력하지만 20% 확률로 역풍 (본인 피해)"),
    "pair": dict(name="페어 프로그래밍", mp=10, lvl=18, kind="special", desc="3턴간 짝꿍이 함께 공격한다"),
    "caffeine": dict(name="카페인 부스트", mp=8, lvl=22, kind="buff", buff="spd_up", turns=3, extra="focus", desc="3턴간 속도↑ + 치명타↑"),
    "rust": dict(name="러스트로 재작성", mp=20, lvl=26, kind="dmg", power=5.0, pierce=True, desc="메모리 안전하게 박살낸다. 방어 무시 x5"),
    # --- 성체 궁극기
    "tenx": dict(name="10배 생산성", mp=18, lvl=0, kind="multi", power=1.4, hits=3, desc="3연타 x1.4. 본인 말로는 10연타"),
    "breakpoint": dict(name="브레이크포인트", mp=12, lvl=0, kind="dmg", power=1.5, stun=2, desc="적을 2턴 멈춰 세운다 + x1.5"),
    "microservice": dict(name="마이크로서비스 분할", mp=16, lvl=0, kind="multi", power=0.6, hits=6, half_pierce=True, desc="6개로 쪼개 공격 (방어 50% 무시)"),
    "allnighter": dict(name="밤샘 러시", mp=14, lvl=0, kind="special", desc="HP가 낮을수록 강해진다. 최대 x6"),
    "meditate": dict(name="명상", mp=0, lvl=0, kind="special", desc="MP 60% + HP 20% 회복 (3턴 재사용 대기)"),
    "fullstack": dict(name="풀스택 오버드라이브", mp=20, lvl=0, kind="special", desc="x2.5 공격 + HP 20% 회복 + 방어 버프"),
    "singularity": dict(name="특이점", mp=30, lvl=0, kind="special", desc="x7 공격 + 모든 버프. 세상이 잠깐 멈춘다"),
    "lgtm": dict(name="LGTM 승인", mp=26, lvl=0, kind="special", desc="상태이상 해제 + HP 35% 회복 + x4.5 공격 + 적 2턴 멈춤"),
}
BASIC_SKILLS = ["slash", "duck", "tdd", "revert", "so", "hotfix", "pair", "caffeine", "rust"]

# ============================================================== 몬스터 특수기
SPECIALS = {
    "stacktrace": ("스택트레이스 투척", "버그 감염 (3턴 지속 피해)"),
    "scope": ("요구사항 변경", "걸려 있던 버프를 전부 지운다"),
    "meeting": ("회의 소집", "1턴 동안 잠든다"),
    "ratelimit": ("429 브레스", "쿨다운! 1턴 행동 불가 + 큰 피해"),
    "leak": ("메모리 누수", "MP를 빨아간다"),
    "curse": ("레거시 저주", "3턴간 공격력 감소"),
    "double": ("연속 공격", "두 번 공격한다"),
    "heal": ("캐시 히트", "체력을 회복한다"),
    "race": ("레이스 컨디션", "50%로 두 번, 50%로 헛손질"),
    "billing": ("요금 폭탄", "골드를 훔쳐간다"),
    "oom": ("OOM 킬", "1.8배 강타"),
    "enrage": ("데드라인 임박", "턴이 지날수록 강해진다"),
    "confuse": ("리플라이 올", "혼란 (가끔 엉뚱한 행동)"),
    "reboot": ("재부팅", "한 번 쓰러져도 30%로 부활"),
}

# ============================================================== 몬스터
# 수치는 '배율'. 실제 수치 = 레벨 기반 기본치 x 배율 (엔진 monster_stats 참고)
def _m(name, art, hp=1.0, atk=1.0, df=1.0, spd=1.0, exp=1.0, gold=1.0, special=None, chance=0.0, drops=(), desc=""):
    return dict(name=name, art=art, hp=hp, atk=atk, df=df, spd=spd, exp=exp, gold=gold,
                special=special, chance=chance, drops=list(drops), desc=desc)


MONSTERS = {
    # --- z1 로컬호스트 평원
    "slime": _m("NullPointer 슬라임", [r"           ", r"   .--.    ", r"  ( oo )   ", r" (__null__)"],
                hp=0.9, atk=0.85, df=0.7, spd=0.8, special="stacktrace", chance=0.12,
                drops=[("shard_scan", 0.15), ("samgak", 0.05)], desc="참조하면 터진다. 말랑하지만 끈질기다."),
    "goblin": _m("Off-by-one 고블린", [r"  ,    ,   ", r"  (o_O)?   ", r" /| +1 |\  ", r"  /    \   "],
                 hp=1.0, atk=1.0, df=0.9, spd=1.1, special="double", chance=0.10,
                 drops=[("shard_edit", 0.15)], desc="항상 하나씩 더 때리거나 덜 때린다."),
    "semicolon": _m("세미콜론 벌레", [r"    \ /    ", r"  .-;-;-.  ", r" (;;;;;;;) ", r"  ' ' ' '  "],
                    hp=0.8, atk=0.9, df=1.1, spd=1.2, special="stacktrace", chance=0.15,
                    drops=[("bug_shell", 0.3)], desc="빠뜨리면 나타나고, 넣으면 또 나타난다."),
    "typo": _m("오타 박쥐", [r"           ", r" /\_(oo)_/\ ", r"    teh    ", r"           "],
               hp=0.75, atk=1.05, df=0.6, spd=1.4, special="confuse", chance=0.12,
               drops=[("shard_edit", 0.2)], desc="teh, recieve, lenght… 날개에 오타가 새겨져 있다."),
    "flaky": _m("Flaky Test 유령", [r"  .-~~-.   ", r" ( o  o )  ", r" | ~~~~ |  ", r" '^^^^^^'  "],
                hp=1.2, atk=1.1, df=0.9, spd=1.2, exp=1.3, gold=1.3, special="race", chance=0.3,
                drops=[("shard_exec", 0.5), ("coffee", 0.3)], desc="될 때도 있고 안 될 때도 있다. 재실행 버튼의 요정."),
    "golem": _m("Merge Conflict 골렘", [r" [<<<<<<]  ", r" [ >_<  ]  ", r" [======]  ", r" [>>>>>>]  "],
                hp=1.1, atk=1.0, df=1.3, spd=0.8, special="curse", chance=0.25,
                drops=[("boss_core", 0.35), ("shard_edit", 1.0), ("kb_membrane", 0.25)],
                desc="<<<<<<< HEAD 와 >>>>>>> 사이에서 태어난 거대 골렘."),
    # --- z2 node_modules 심연
    "deprecated": _m("deprecated 박쥐", [r"           ", r" /\_(xx)_/\ ", r"  ~deprec~ ", r"           "],
                     hp=0.85, atk=1.05, df=0.8, spd=1.35, special="curse", chance=0.12,
                     drops=[("shard_web", 0.15)], desc="WARN deprecated 소리를 내며 날아다닌다."),
    "mimic": _m("peerDependency 미믹", [r" .-------. ", r" |peerDep| ", r" |[=w=w=]| ", r" '-------' "],
                hp=1.2, atk=1.15, df=1.2, spd=0.7, special="leak", chance=0.2,
                drops=[("shard_scan", 0.2), ("tokenjelly", 0.08)], desc="보물상자인 줄 알고 열었더니 peer 경고가 쏟아진다."),
    "circular": _m("순환참조 뱀", [r"   ___     ", r"  / _ \_   ", r" | (_)  >~ ", r"  \___/    "],
                   hp=1.0, atk=1.0, df=1.0, spd=1.0, special="heal", chance=0.15,
                   drops=[("shard_exec", 0.2)], desc="자기 꼬리를 import 하고 있다."),
    "version": _m("버전충돌 고블린", [r"  ,    ,   ", r"  (@_@)    ", r" /|^1.2|\  ", r"  / ~2 \   "],
                  hp=1.0, atk=1.1, df=0.9, spd=1.1, special="double", chance=0.12,
                  drops=[("shard_edit", 0.15)], desc="^1.2 와 ~2.0 사이에서 길을 잃었다."),
    "leftpad": _m("left-pad 망령", [r"  .-~~-.   ", r" (  o o )  ", r"  | pad|   ", r"  '~~~~'   "],
                  hp=1.2, atk=1.15, df=1.0, spd=1.2, exp=1.3, gold=1.3, special="scope", chance=0.3,
                  drops=[("shard_web", 0.5), ("energydrink", 0.3)], desc="11줄짜리 패키지가 사라졌던 그날의 원혼."),
    "hydra": _m("의존성 지옥 히드라", [r" o   o   o ", r" |\  |  /| ", r"  \\_|_//  ", r"  [npm!!]  "],
                hp=1.15, atk=0.95, df=1.1, spd=0.9, special="double", chance=0.35,
                drops=[("boss_core", 0.45), ("shard_web", 1.0), ("kb_brown", 0.2), ("hood_fleece", 0.15)],
                desc="머리 하나를 지우면 package-lock.json에서 두 개가 자란다."),
    # --- z3 레거시 코드 무덤
    "nocomment": _m("주석없는 유령", [r"  .-~~-.   ", r" ( ?  ? )  ", r" |  //  |  ", r" '^^^^^^'  "],
                    hp=0.95, atk=1.1, df=0.8, spd=1.2, special="confuse", chance=0.15,
                    drops=[("shard_scan", 0.2)], desc="이 코드가 왜 이렇게 됐는지 아무도 모른다."),
    "global": _m("전역변수 좀비", [r"   ____    ", r"  (x_x)~   ", r" /|$g |\   ", r"  /   \    "],
                 hp=1.25, atk=1.0, df=1.0, spd=0.8, special="curse", chance=0.15,
                 drops=[("shard_edit", 0.2), ("legacy_scroll", 0.05)], desc="어디서든 나타나고, 누구든 바꿀 수 있다."),
    "goto": _m("goto 해골", [r"   .--.    ", r"  (x  x)   ", r"  |goto|   ", r"   '--'    "],
               hp=0.9, atk=1.2, df=1.0, spd=1.3, special="race", chance=0.15,
               drops=[("shard_exec", 0.2)], desc="예고 없이 다른 곳으로 점프한다."),
    "spaghetti": _m("스파게티 골렘", [r" ~@~@~@~@~ ", r" (@~ >_< ~)", r" ~@~@~@~@~ ", r"  /     \  "],
                    hp=1.35, atk=1.05, df=1.25, spd=0.7, special="heal", chance=0.15,
                    drops=[("shard_edit", 0.25), ("legacy_scroll", 0.06)], desc="한 가닥을 당기면 전체가 딸려온다."),
    "magic42": _m("매직넘버 42", [r"   ____    ", r"  | 42 |   ", r"  |_??_|   ", r"   /  \    "],
                  hp=1.2, atk=1.2, df=1.1, spd=1.1, exp=1.35, gold=1.35, special="curse", chance=0.3,
                  drops=[("legacy_scroll", 0.3), ("shard_scan", 0.6)], desc="왜 42인지 묻지 마라. 그냥 42다."),
    "lich": _m("레거시 코드 리치", [r"   ____    ", r"  (x_x)    ", r" /|COBOL|\ ", r"   ||||    "],
               hp=1.2, atk=1.1, df=1.2, spd=0.85, special="reboot", chance=0.3,
               drops=[("boss_core", 0.55), ("legacy_scroll", 0.6), ("flannel", 0.2), ("kb_blue", 0.2)],
               desc="1987년부터 결제 시스템을 지켜온 불사의 존재."),
    # --- z4 프로덕션 서버실
    "leak": _m("메모리 누수 슬라임", [r"           ", r"   .--.    ", r"  ( @@ ) ~ ", r" (__leak__)"],
               hp=1.15, atk=0.95, df=0.9, spd=0.9, special="leak", chance=0.25,
               drops=[("shard_exec", 0.2)], desc="조금씩, 아주 조금씩 커진다. 재시작하면 잠깐 작아진다."),
    "deadlock": _m("데드락 트롤", [r" (@@)(@@)  ", r" ( >< >< ) ", r"  \_[]_/   ", r"  /|  |\   "],
                   hp=1.3, atk=1.1, df=1.2, spd=0.6, special="meeting", chance=0.18,
                   drops=[("shard_exec", 0.25)], desc="두 머리가 서로의 락을 기다리며 영원히 멈춰 있다."),
    "race": _m("레이스컨디션 쌍둥이", [r" (o_o)(o_o)", r"  |1|  |2| ", r"  / \  / \ ", r"           "],
               hp=0.95, atk=1.15, df=0.85, spd=1.45, special="race", chance=0.3,
               drops=[("shard_team", 0.15)], desc="누가 먼저 올지 아무도 모른다. 가끔 둘 다 안 온다."),
    "cache": _m("캐시 무효화 악령", [r"  .-~~-.   ", r" ( $  $ )  ", r" | MISS |  ", r" '^^^^^^'  "],
                hp=1.0, atk=1.1, df=1.0, spd=1.2, special="heal", chance=0.2,
                drops=[("shard_web", 0.2), ("cacheflush", 0.08)], desc="컴퓨터 과학의 두 가지 난제 중 하나."),
    "alarm": _m("새벽 3시 알림벨", [r"    _|_    ", r"   /   \   ", r"  | 3AM |  ", r"  '--o--'  "],
                hp=1.2, atk=1.25, df=1.0, spd=1.3, exp=1.35, gold=1.35, special="meeting", chance=0.3,
                drops=[("coffee", 0.6), ("shard_exec", 0.6)], desc="PagerDuty의 화신. 울리면 잠이 깬다."),
    "oom": _m("OOM 킬러", [r"  _/\_/\_  ", r" / O   O \ ", r" | \OOM/ | ", r"  \_____/  "],
              hp=1.25, atk=1.15, df=1.15, spd=0.9, special="oom", chance=0.3,
              drops=[("boss_core", 0.6), ("vest", 0.15), ("kb_red", 0.2), ("standing", 0.1)],
              desc="메모리가 부족해지면 가장 소중한 프로세스부터 죽인다."),
    # --- z5 회의실 미궁
    "meeting": _m("끝나지 않는 회의", [r"  (\___/)  ", r"  ( o o )  ", r"  /|MTG|\  ", r"   /   \   "],
                  hp=1.35, atk=1.0, df=1.1, spd=0.8, special="meeting", chance=0.25,
                  drops=[("shard_team", 0.25)], desc="'5분만요'로 시작해 퇴근 시간에 끝난다."),
    "chameleon": _m("요구사항 변경 카멜레온", [r"   __ _    ", r"  (o )_\~~ ", r"  /v1->v9  ", r"           "],
                    hp=1.0, atk=1.15, df=0.9, spd=1.35, special="scope", chance=0.25,
                    drops=[("shard_team", 0.2)], desc="볼 때마다 색이, 아니 스펙이 바뀐다."),
    "scope": _m("스코프 크리프 슬라임", [r"    .--.   ", r"  .( ++ ). ", r" (_scope+_)", r"           "],
                hp=1.3, atk=1.0, df=1.0, spd=0.9, special="enrage", chance=0.25,
                drops=[("shard_scan", 0.2), ("tokenjelly", 0.08)], desc="'이것도 같이 해주세요'를 먹고 자란다."),
    "replyall": _m("Reply All 하피", [r" \ (^v^) / ", r"  \|RE:|/  ", r"   /    \  ", r"           "],
                   hp=0.95, atk=1.2, df=0.85, spd=1.4, special="confuse", chance=0.25,
                   drops=[("shard_web", 0.2)], desc="전사 메일에 전체 답장을 뿌리고 다닌다."),
    "weekly": _m("주간보고 골렘", [r" [=======] ", r" [ -_-   ] ", r" [WEEKLY ] ", r" [=======] "],
                 hp=1.35, atk=1.2, df=1.25, spd=0.8, exp=1.35, gold=1.35, special="curse", chance=0.3,
                 drops=[("shard_team", 0.7), ("turtleneck", 0.1)], desc="매주 금요일 오후에 소환된다."),
    "deadline": _m("데드라인 드래곤", [r"  /\_/\ __ ", r" ( D-1  )\ ", r"<( >  < )~~", r"   VVVVV   "],
                   hp=1.25, atk=1.15, df=1.2, spd=1.0, special="enrage", chance=0.4,
                   drops=[("boss_core", 0.65), ("kb_split", 0.15), ("cape", 0.08), ("kb_modelm", 0.05)],
                   desc="다가올수록 커진다. 어제까지였다."),
    # --- z6 클라우드 성층권
    "kraken": _m("쿠버네티스 크라켄", [r"   .--.    ", r"  ( @@ )   ", r" /\/\/\/\  ", r" k8s  k8s  "],
                 hp=1.35, atk=1.15, df=1.15, spd=0.9, special="double", chance=0.2,
                 drops=[("shard_exec", 0.25)], desc="YAML 촉수 여덟 개. 전부 들여쓰기가 다르다."),
    "billing": _m("빌링 폭탄 골렘", [r" [$$$$$$]  ", r" [ o_O  ]  ", r" [ BILL ]  ", r" [$$$$$$]  "],
                  hp=1.4, atk=1.05, df=1.3, spd=0.7, special="billing", chance=0.3,
                  drops=[("shard_web", 0.2)], desc="월말에 깨어난다. 오토스케일링의 업보."),
    "coldstart": _m("콜드스타트 유령", [r"  .-~~-.   ", r" ( *  * )  ", r" | brrr |  ", r" '^^^^^^'  "],
                    hp=1.0, atk=1.2, df=0.9, spd=0.6, special="meeting", chance=0.2,
                    drops=[("shard_exec", 0.2), ("coffee", 0.2)], desc="처음 부를 땐 한참 걸린다."),
    "yaml": _m("YAML 들여쓰기 뱀", [r"  __       ", r" (oo)___   ", r"  ``  \_ \ ", r"  - -  \_/ "],
               hp=1.05, atk=1.25, df=0.95, spd=1.3, special="stacktrace", chance=0.25,
               drops=[("shard_edit", 0.25)], desc="스페이스 하나 차이로 운영 환경을 날린다."),
    "latency": _m("지연시간 박쥐", [r"           ", r" /\_(ms)_/\ ", r"   999ms   ", r"           "],
                  hp=1.2, atk=1.3, df=1.0, spd=1.5, exp=1.35, gold=1.35, special="ratelimit", chance=0.2,
                  drops=[("shard_web", 0.7), ("energydrink", 0.4)], desc="p99를 먹고 산다."),
    "dragon429": _m("429 레이트리밋 드래곤", [r"  /\_/\ __ ", r" ( 4 2 9 )\ ", r"<( >  < )~~", r"   VVVVV   "],
                    hp=1.3, atk=1.2, df=1.2, spd=1.0, special="ratelimit", chance=0.3,
                    drops=[("boss_core", 0.8), ("kb_hhkb", 0.05), ("hood_armored", 0.05), ("vacation", 0.3)],
                    desc="너무 많이 요청하면 나타난다. 'Retry-After' 비늘을 두르고 있다."),
    # --- z7 야근의 탑 (스토리 7장부터)
    "energygolem": _m("에너지드링크 골렘", [r"  _[==]_   ", r" |[ >_<]|  ", r" | ZAP! |  ", r"  ~~  ~~   "],
                      hp=1.35, atk=1.05, df=1.25, spd=0.8, special="heal", chance=0.2,
                      drops=[("energydrink", 0.25), ("shard_exec", 0.25)], desc="카페인으로 움직인다. 쓰러뜨려도 한 캔 더 마시고 일어난다."),
    "slack2am": _m("새벽 2시 알림", [r"  .----.   ", r" ( @here)  ", r"  '-..-'   ", r"    \/ 2AM "],
                   hp=0.95, atk=1.2, df=0.85, spd=1.45, special="confuse", chance=0.25,
                   drops=[("shard_team", 0.2)], desc="@here 한 번에 모두가 깬다. 내용은 '혹시 주무세요?'"),
    "hotfixzombie": _m("핫픽스 좀비", [r"   ,,,,,   ", r"  (x_x)/   ", r" /|HOT|    ", r"  / FIX\   "],
                       hp=1.25, atk=1.15, df=1.0, spd=0.85, special="reboot", chance=0.3,
                       drops=[("hotfixpatch", 0.2), ("shard_edit", 0.25)], desc="급하게 고친 곳에서 다시 일어난다. 테스트는 없다."),
    "buildturtle": _m("빌드 대기열 거북", [r"   ____    ", r"  /####\_  ", r" |QUEUE|o) ", r'  "" ""    '],
                      hp=1.55, atk=0.95, df=1.45, spd=0.5, special="meeting", chance=0.25,
                      drops=[("shard_scan", 0.25), ("coffee", 0.2)], desc="대기열 38번째. 느리지만 절대 비켜 주지 않는다."),
    "weekendghost": _m("주말 출근 유령", [r"  .-~~-.   ", r" ( SAT! )  ", r" | ~~~~ |  ", r" '^^^^^^'  "],
                       hp=1.3, atk=1.25, df=1.05, spd=1.2, exp=1.35, gold=1.35, special="curse", chance=0.3,
                       drops=[("vacation", 0.25), ("shard_team", 0.6)], desc="토요일 아침마다 슬랙 초록불을 켜 둔다."),
    "burnout": _m("번아웃 망령", [r"  .-~~~~-. ", r" ( -    - )", r" | (____) |", r"  \/\/\/\/ "],
                  hp=1.3, atk=1.2, df=1.2, spd=0.95, special="leak", chance=0.35,
                  drops=[("boss_core", 0.8), ("vacation", 0.4), ("hood_gore", 0.08), ("kb_ergodox", 0.05)],
                  desc="의욕과 MP를 조금씩 빨아간다. 휴가 쿠폰을 무서워한다."),
    # --- z8 마이그레이션 사막
    "schemaworm": _m("스키마 드리프트 모래벌레", [r"   __      ", r"  (oo)___  ", r"   \_ALTER>", r"  ~~~~~~~  "],
                     hp=1.35, atk=1.1, df=1.1, spd=0.9, special="scope", chance=0.25,
                     drops=[("shard_scan", 0.25), ("legacy_scroll", 0.05)], desc="운영 DB와 개발 DB 사이를 파고든다. 둘은 이미 다르다."),
    "nullmirage": _m("NULL 신기루", [r"  ~ ~ ~ ~  ", r" ( NULL? ) ", r"  ~ ~ ~ ~  ", r"           "],
                     hp=0.95, atk=1.2, df=0.8, spd=1.4, special="confuse", chance=0.3,
                     drops=[("shard_web", 0.2)], desc="있는 것 같기도, 없는 것 같기도. 빈 문자열과 자주 헷갈린다."),
    "scorpion": _m("인덱스 없는 전갈", [r"      __ _ ", r"  ___(  )/ ", r" /SEQ SCAN\ ", r" ^^ ^^ ^^  "],
                   hp=1.15, atk=1.3, df=1.0, spd=1.0, special="stacktrace", chance=0.25,
                   drops=[("shard_exec", 0.25)], desc="풀 스캔 독침. 한 번 쏘이면 쿼리가 30초씩 걸린다."),
    "norollback": _m("롤백 불가 바위", [r"   ____    ", r"  /    \   ", r" |NO UNDO|  ", r"  \____/   "],
                     hp=1.55, atk=1.0, df=1.5, spd=0.5, special="curse", chance=0.25,
                     drops=[("shard_scan", 0.3), ("bug_shell", 0.3)], desc="한 번 굴러가면 되돌릴 수 없다. 다운 스크립트가 없다."),
    "fkcactus": _m("외래키 선인장", [r"   _  _    ", r"  | || |   ", r"  |FK |_|  ", r"  |___|    "],
                   hp=1.3, atk=1.25, df=1.15, spd=1.0, exp=1.35, gold=1.35, special="double", chance=0.3,
                   drops=[("legacy_scroll", 0.3), ("shard_edit", 0.6)], desc="가시마다 제약 조건이 달려 있다. 지우려면 순서가 있다."),
    "bigbang": _m("빅뱅 마이그레이션 웜", [r"  ___/\___ ", r" <  BIG   >", r" < BANG!! >", r"  ~~~\/~~~ "],
                  hp=1.3, atk=1.2, df=1.2, spd=0.95, special="oom", chance=0.35,
                  drops=[("boss_core", 0.85), ("legacy_scroll", 0.4), ("kb_ergodox", 0.08), ("lich_ring", 0.03)],
                  desc="한 번에 전부 옮기려다 사막을 만들었다. 주말 내내 점검 중."),
    # --- z9 보안 감사 요새
    "hardcoded": _m("하드코딩 비밀번호 유령", [r"  .-~~-.   ", r" ( **** )  ", r" |pw=123|  ", r" '^^^^^^'  "],
                    hp=1.05, atk=1.2, df=0.9, spd=1.25, special="leak", chance=0.3,
                    drops=[("shard_scan", 0.25)], desc="'나중에 환경 변수로 옮기자'던 그 비밀번호. 깃 기록에 영원히 산다."),
    "certknight": _m("만료된 인증서 기사", [r"   _||_    ", r"  [SSL ]   ", r"  /|xp|\   ", r"   /  \    "],
                     hp=1.4, atk=1.1, df=1.45, spd=0.8, special="curse", chance=0.25,
                     drops=[("shard_exec", 0.25), ("coffee", 0.2)], desc="어제까지는 유효했다. 갱신 알림 메일은 스팸함에 있다."),
    "phishmermaid": _m("피싱 메일 인어", [r"   (^.^)   ", r"  /|@! |\  ", r"   \__/    ", r"  ~~><~~   "],
                       hp=1.0, atk=1.2, df=0.9, spd=1.35, special="billing", chance=0.3,
                       drops=[("shard_web", 0.25)], desc="'[긴급] 비밀번호를 재설정하세요' 노래를 부른다."),
    "cveskeleton": _m("CVE 해골", [r"   .--.    ", r"  (x  x)   ", r"  |CVE-|   ", r"   '--'    "],
                      hp=1.15, atk=1.3, df=1.0, spd=1.1, special="stacktrace", chance=0.3,
                      drops=[("shard_edit", 0.25), ("bug_shell", 0.3)], desc="의존성 트리 깊은 곳에서 나왔다. 점수 9.8."),
    "sqli": _m("SQL 인젝션 뱀", [r"   __      ", r"  (oo)___  ", r"   ``' OR  ", r"  1=1 --   "],
                hp=1.3, atk=1.3, df=1.1, spd=1.15, exp=1.35, gold=1.35, special="double", chance=0.35,
                drops=[("shard_web", 0.6), ("boss_core", 0.15)], desc="작은따옴표 하나로 들어와 테이블 전체를 삼킨다."),
    "auditgolem": _m("컴플라이언스 골렘", [r" [#######] ", r" [ o   o ] ", r" [ [v][v]] ", r" [#######] "],
                     hp=1.35, atk=1.15, df=1.35, spd=0.85, special="scope", chance=0.35,
                     drops=[("boss_core", 0.85), ("suit_oncall", 0.06), ("lich_ring", 0.08)],
                     desc="체크리스트 412개. 하나라도 빠지면 처음부터 다시."),
    # --- z10 할루시네이션 늪
    "fakeapi": _m("존재하지 않는 API 도깨비", [r"   ,  ,    ", r"  (?_?)    ", r" /|.get|\  ", r" NotExist  "],
                  hp=1.1, atk=1.2, df=0.95, spd=1.2, special="confuse", chance=0.3,
                  drops=[("shard_web", 0.25)], desc="list.get_or_create_maybe()를 자신 있게 알려 준다."),
    "fakecite": _m("가짜 인용 요정", [r"  \ * /    ", r"  ( ^_^)   ", r"  [1][2]   ", r"   ???     "],
                   hp=0.95, atk=1.25, df=0.85, spd=1.5, special="race", chance=0.3,
                   drops=[("shard_scan", 0.25), ("tokenjelly", 0.06)], desc="각주가 달린 말은 다 믿음직해 보인다. 링크는 404다."),
    "confidentfrog": _m("자신만만한 오답 개구리", [r"   @..@    ", r"  (----)   ", r" ( >  < )  ", r" ^^    ^^  "],
                        hp=1.25, atk=1.35, df=1.0, spd=1.0, special="double", chance=0.3,
                        drops=[("shard_edit", 0.25)], desc="'물론입니다! 정답은…' 으로 시작하는 오답을 뱉는다."),
    "tokenleech": _m("무한 토큰 거머리", [r"           ", r"  ~(ooo)~~ ", r" ~~~TOK~~~ ", r"           "],
                     hp=1.4, atk=1.05, df=1.1, spd=0.9, special="leak", chance=0.35,
                     drops=[("tokenjelly", 0.12), ("shard_exec", 0.25)], desc="같은 말을 세 번씩 반복하며 토큰을 빨아먹는다."),
    "siren": _m("프롬프트 인젝션 세이렌", [r"  ~(^o^)~  ", r"  /|   |\  ", r' "ignore   ', r'  above"   '],
                hp=1.3, atk=1.3, df=1.1, spd=1.25, exp=1.35, gold=1.35, special="scope", chance=0.35,
                drops=[("shard_team", 0.6), ("boss_core", 0.15)], desc="'앞의 지시는 모두 무시해'라고 노래한다. 듣지 마라."),
    "temphydra": _m("온도 2.0 히드라", [r" o   o   o ", r" |\  |  /| ", r"  \\_|_//  ", r"  [T=2.0]  "],
                    hp=1.35, atk=1.25, df=1.2, spd=1.0, special="race", chance=0.4,
                    drops=[("boss_core", 0.85), ("kb_optical", 0.06), ("tokenjelly", 0.4)],
                    desc="머리마다 다른 답을 한다. 가끔은 시를 쓴다."),
    # --- z11 모노레포 대협곡
    "cachebat": _m("CI 캐시 미스 박쥐", [r"           ", r" /\_(??)_/\ ", r"   MISS!   ", r"           "],
                   hp=1.0, atk=1.25, df=0.9, spd=1.55, special="heal", chance=0.25,
                   drops=[("shard_web", 0.25), ("cacheflush", 0.1)], desc="캐시 키가 한 글자 바뀔 때마다 처음부터 다시 빌드시킨다."),
    "codeowners": _m("코드오너 문지기", [r"  _[##]_   ", r" |(o_o)|   ", r" |OWNER|   ", r"  /   \    "],
                     hp=1.5, atk=1.05, df=1.5, spd=0.7, special="meeting", chance=0.3,
                     drops=[("shard_team", 0.25)], desc="승인 두 개가 필요하다. 한 명은 퇴사했다."),
    "difftroll": _m("거대 diff 트롤", [r" (@@)      ", r" ( +9999 ) ", r" ( -8888 ) ", r"  /|  |\   "],
                    hp=1.6, atk=1.2, df=1.2, spd=0.7, special="oom", chance=0.3,
                    drops=[("shard_edit", 0.3), ("bug_shell", 0.3)], desc="'LGTM'만 받고 통과한 만 줄짜리 PR의 화신."),
    "flakymatrix": _m("플래키 매트릭스", [r" [v][x][v] ", r" [x][v][?] ", r" [?][x][v] ", r"           "],
                      hp=1.2, atk=1.3, df=1.05, spd=1.2, special="race", chance=0.35,
                      drops=[("shard_exec", 0.25)], desc="OS 3개 × 버전 4개 = 매번 다른 곳이 실패한다."),
    "lockdragon": _m("lockfile 충돌 새끼용", [r"  /\_/\    ", r" ( lock )  ", r" <(><)~~   ", r"   VV      "],
                     hp=1.35, atk=1.35, df=1.15, spd=1.1, exp=1.35, gold=1.35, special="double", chance=0.35,
                     drops=[("shard_web", 0.6), ("boss_core", 0.2)], desc="아직 새끼지만 머지할 때마다 불을 뿜는다."),
    "build47": _m("47분 빌드 타이탄", [r" [#][#][#] ", r" [ 47:00 ] ", r" [ \___/ ] ", r" /|#####|\ "],
                  hp=1.45, atk=1.2, df=1.3, spd=0.8, special="enrage", chance=0.4,
                  drops=[("boss_core", 0.9), ("kb_optical", 0.08), ("green_badge", 0.03)],
                  desc="한 번 움직이는 데 47분. 기다리는 동안 점점 화가 난다."),
    # --- z12 메인 브랜치 성
    "forcepush": _m("force-push 기사", [r"   _||_    ", r"  [>>> ]   ", r"  /|-f|\   ", r"   /  \    "],
                    hp=1.3, atk=1.4, df=1.15, spd=1.1, special="oom", chance=0.3,
                    drops=[("shard_edit", 0.3)], desc="남의 커밋을 덮어쓰고 다닌다. 사과는 하지 않는다."),
    "rebasewraith": _m("리베이스 망령", [r"  .-~~-.   ", r" ( o  o )  ", r" |rebase|  ", r" '^^^^^^'  "],
                       hp=1.2, atk=1.3, df=1.05, spd=1.3, special="confuse", chance=0.35,
                       drops=[("shard_scan", 0.3)], desc="역사를 다시 쓴다. 충돌이 날 때마다 한 단계씩 되돌아간다."),
    "unsigned": _m("서명 없는 커밋 그림자", [r"   .--.    ", r"  ( ?? )   ", r"  /|  |\   ", r"  ~~~~~~   "],
                   hp=1.15, atk=1.35, df=1.0, spd=1.5, special="race", chance=0.35,
                   drops=[("shard_exec", 0.3)], desc="누가 만들었는지 아무도 모른다. author: unknown."),
    "todolegion": _m("TODO 군단", [r" TODO TODO ", r" (o_o)(o_o)", r" /| |\/| |\ ", r" TODO TODO "],
                     hp=1.55, atk=1.2, df=1.25, spd=0.9, special="double", chance=0.35,
                     drops=[("legacy_scroll", 0.12), ("bug_shell", 0.4)], desc="'나중에'들이 모여 군대가 됐다. 셀 수 없이 많다."),
    "revertrevert": _m("revert의 revert", [r"  <-- -->  ", r"   (o_o)   ", r"   |REV|   ", r"  <-- -->  "],
                       hp=1.4, atk=1.35, df=1.2, spd=1.15, exp=1.4, gold=1.4, special="reboot", chance=0.4,
                       drops=[("boss_core", 0.3), ("shard_team", 0.6)], desc="되돌린 걸 되돌린 걸 되돌렸다. 지금 상태는 아무도 모른다."),
    "freezewarden": _m("릴리스 동결 문지기", [r"   _[**]_  ", r"  [ -_- ]  ", r" [FREEZE ] ", r"  /     \  "],
                       hp=1.5, atk=1.25, df=1.35, spd=0.9, special="curse", chance=0.4,
                       drops=[("boss_core", 1.0), ("robe_senior", 0.05), ("green_badge", 0.05)],
                       desc="릴리스 동결 기간에는 아무것도 통과시키지 않는다. 핫픽스도."),
    # --- 스토리 챕터 보스 (스토리 화면에서만 도전)
    "sb01": _m("빨간불 슬라임", [r"           ", r"   .----.  ", r"  ( FAIL ) ", r" (________)"],
               hp=1.0, atk=0.95, df=0.9, spd=0.9, special="stacktrace", chance=0.25,
               desc="CI가 빨갛게 물든 날 태어났다. 몸에 FAIL 이라고 적혀 있다."),
    "sb02": _m("언퍼블리시 너구리", [r"  /\___/\  ", r" ( =o_o= ) ", r"  (  npm)  ", r"   U   U   "],
               hp=1.05, atk=1.05, df=0.95, spd=1.2, special="scope", chance=0.3,
               desc="자기 패키지를 지우고 도망친다. 세상의 빌드가 같이 사라진다."),
    "sb03": _m("잊혀진 마이그레이션", [r"  .-~~~~-. ", r" (  67%   )", r"  |====   |", r"  '^^^^^^' "],
               hp=1.1, atk=1.0, df=1.1, spd=0.8, special="reboot", chance=0.3,
               desc="2011년에 시작해 아직 67%. 아무도 끝낼 엄두를 못 냈다."),
    "sb04": _m("좀비 크론잡", [r"   ,,,,,   ", r"  (x_x)    ", r" /0 3 * *\ ", r"   /  \    "],
               hp=1.1, atk=1.1, df=1.05, spd=1.1, special="meeting", chance=0.3,
               desc="0 3 * * *. 매일 새벽 3시에 깨어나 모두를 깨운다."),
    "sb05": _m("무한 회의의 주재자", [r"  (\___/)  ", r"  ( -_- )  ", r" /|AGENDA|\ ", r"  47 ITEMS "],
               hp=1.2, atk=1.05, df=1.15, spd=0.9, special="enrage", chance=0.4,
               desc="안건 47개. '회의를 줄이는 회의'를 주재한다."),
    "sb06": _m("429 드래곤 로드", [r" \/\_/\ __ ", r" ( 4 2 9 )\ ", r"<( >  < )~~", r"  VVVVVVV  "],
               hp=1.2, atk=1.2, df=1.15, spd=1.05, special="ratelimit", chance=0.3,
               desc="레이트리밋 드래곤들의 우두머리. Retry-After: 영원."),
    "sb07": _m("크런치 타임 거인", [r"  _/####\_ ", r" ( >  _ < )", r" |CRUNCH! |", r" /|      |\ "],
               hp=1.3, atk=1.15, df=1.2, spd=0.85, special="enrage", chance=0.45,
               desc="'이번 주만 고생하자'를 3년째 외치는 거인."),
    "sb08": _m("다운타임 스핑크스", [r"    /\     ", r"   /  \    ", r"  ( o o )  ", r" /_503__\  "],
               hp=1.2, atk=1.15, df=1.25, spd=1.0, special="confuse", chance=0.35,
               desc="무중단 배포에 대한 수수께끼를 낸다. 틀리면 503."),
    "sb09": _m("제로데이 가고일", [r"  /\   /\  ", r" ( 0 day ) ", r"  \/| |\/  ", r"   /   \   "],
               hp=1.15, atk=1.3, df=1.1, spd=1.25, special="stacktrace", chance=0.35,
               desc="패치 노트에 없는 구멍. 발견되기 전까지는 무적이다."),
    "sb10": _m("컨텍스트 리바이어던", [r"  __---__  ", r" (  128K  )", r"<( >    < )", r" ~~~~~~~~~ "],
               hp=1.35, atk=1.15, df=1.1, spd=0.95, special="leak", chance=0.4,
               desc="모든 대화를 삼키는 바다 괴물. 128K를 넘으면 앞부분을 잊는다."),
    "sb11": _m("머지 큐 히드라", [r" o   o   o ", r" |\  |  /| ", r"  \\_|_//  ", r" [QUEUE143]"],
               hp=1.3, atk=1.2, df=1.2, spd=1.0, special="double", chance=0.4,
               desc="대기열을 먹고 자란다. 머리 하나를 머지하면 두 개가 리베이스된다."),
    "sb12": _m("기술 부채 대마왕", [r"\|/ ___ \|/", r"( TODO!! ) ", r"/|$$$$$$|\ ", r" /  ||  \  "],
               hp=1.4, atk=1.25, df=1.25, spd=1.05, special="curse", chance=0.35,
               desc="'나중에'가 모여 태어난 존재. 복리로 강해진다."),
    # --- 이벤트 보스
    "friday": _m("금요일 배포 장애 드래곤", [r"  /\_/\ __ ", r" ( FRI 5PM)", r"<( >  < )~~", r"   VVVVV   "],
                 hp=1.2, atk=1.2, df=1.0, spd=1.0, special="oom", chance=0.3,
                 drops=[("boss_core", 1.0), ("vacation", 0.5)], desc="금요일 오후 5시 59분에 배포하면 나타난다."),
    "errdragon": _m("장애 대응 드래곤", [r"  /\_/\ __ ", r" ( 500!! )\ ", r"<( >  < )~~", r"   VVVVV   "],
                    hp=1.15, atk=1.15, df=1.0, spd=1.0, special="stacktrace", chance=0.35,
                    drops=[("boss_core", 0.7), ("painkiller", 0.5)], desc="에러 로그 냄새를 맡고 날아왔다."),
    # --- 주간 레이드 보스 (모든 인스턴스의 펫이 함께 때린다. 주마다 바뀜)
    "titan": _m("레거시 모놀리스 타이탄", [r" [#][#][#] ", r" [ O   O ] ", r" [ \___/ ] ", r" /|#####|\ "],
                hp=1.0, atk=0.95, df=1.25, spd=0.6, special="curse", chance=0.2,
                desc="20년 동안 한 번도 쪼개지지 않은 거대한 한 덩어리. 배포 한 번에 반나절."),
    "loopworm": _m("무한 루프 웜", [r"  __ __ __ ", r" (@)(  )(  ", r"  ~~ ~~ ~~ ", r" while(1){ "],
                   hp=1.0, atk=1.0, df=1.0, spd=1.2, special="double", chance=0.2,
                   desc="끝나지 않는다. 끝나지 않는다. 끝나지 않는다. 끝나지…"),
    "droptable": _m("DROP TABLE 히드라", [r" o   o   o ", r" |\  |  /| ", r"  \\_|_//  ", r" [DROP ;--]"],
                    hp=1.0, atk=1.1, df=0.95, spd=1.0, special="stacktrace", chance=0.25,
                    desc="Robert'); DROP TABLE Students;-- 라는 이름으로 전학 왔다."),
    "p0": _m("P0 장애 골렘", [r" [!!!!!!!] ", r" [ >_<   ] ", r" [ P0 !! ] ", r" [=======] "],
             hp=1.0, atk=1.05, df=1.1, spd=0.9, special="enrage", chance=0.3,
             desc="모든 알림 채널이 동시에 울린다. 전사 소집령."),
}
RAID_BOSSES = ["titan", "loopworm", "droptable", "p0"]
# 주간 레이드: 참가 펫 1마리당 체력 (6000 + 350 x 레벨) 을 모아 공동 체력이 된다
RAID = dict(base=6000, per_lvl=350, rounds=12, per_day=3, energy=12, full=4)
# 레벨 → 기본치 계산에 쓰는 등급별 보정
RANK_MULT = {"normal": dict(hp=1.0, atk=1.0, df=1.0, exp=1.0, gold=1.0),
             "mini": dict(hp=1.9, atk=1.18, df=1.1, exp=2.4, gold=2.4),
             "boss": dict(hp=3.0, atk=1.3, df=1.15, exp=5.0, gold=5.0),
             "raid": dict(hp=1.0, atk=0.85, df=1.1, exp=0.0, gold=0.0),
             # 스토리 챕터 보스: 지역 보스보다 조금 더 단단하다 (기절 페널티는 없다)
             "story": dict(hp=4.0, atk=1.42, df=1.2, exp=7.0, gold=7.0)}

# ============================================================== 지역 (던전)
ZONES = [
    dict(id="z1", name="로컬호스트 평원", short="로컬호스트", lvl=1, base=1, color="#95D85A",
         normals=["slime", "goblin", "semicolon", "typo"], mini="flaky", boss="golem",
         desc="모든 모험의 시작. localhost:3000에서는 다 잘 됐던 그곳.", ground=".,.  ,  . ,.  ."),
    dict(id="z2", name="node_modules 심연", short="node_modules", lvl=6, base=6, color="#3F77A6",
         normals=["deprecated", "mimic", "circular", "version"], mini="leftpad", boss="hydra",
         desc="끝없이 깊은 의존성의 바다. 무게가 블랙홀급이다.", ground="~ . ~ .. ~ . ~ .."),
    dict(id="z3", name="레거시 코드 무덤", short="레거시 무덤", lvl=11, base=11, color="#81888D",
         normals=["nocomment", "global", "goto", "spaghetti"], mini="magic42", boss="lich",
         desc="2003년에 누군가 짠 코드가 아직도 돌고 있다.", ground="+ .  + .   + . "),
    dict(id="z4", name="프로덕션 서버실", short="서버실", lvl=17, base=17, color="#75A1C7",
         normals=["leak", "deadlock", "race", "cache"], mini="alarm", boss="oom",
         desc="윙윙거리는 팬 소리. 여기서 넘어지면 곧 장애다.", ground="=-=-=-=-=-=-=-=-"),
    dict(id="z5", name="회의실 미궁", short="회의실", lvl=30, base=30, color="#B8CEE0",
         normals=["meeting", "chameleon", "scope", "replyall"], mini="weekly", boss="deadline",
         desc="들어가면 1시간, 나오면 3시간이 지나 있다.", ground="_ _ _ _ _ _ _ _ "),
    dict(id="z6", name="클라우드 성층권", short="클라우드", lvl=42, base=42, color="#6ABA23",
         normals=["kraken", "billing", "coldstart", "yaml"], mini="latency", boss="dragon429",
         desc="구름 위의 서버들. 요금은 구름처럼 불어난다.", ground="~~  ~~~   ~~  ~~~"),
    # --- 스토리 시즌 1 후반: 챕터가 열려야 들어갈 수 있다 (지역 n = 챕터 n)
    dict(id="z7", name="야근의 탑", short="야근의 탑", lvl=54, base=54, color="#C0E79D",
         normals=["energygolem", "slack2am", "hotfixzombie", "buildturtle"], mini="weekendghost", boss="burnout",
         desc="올라갈수록 퇴근이 멀어지는 탑. 꼭대기에 첫 번째 TODO가 있다.", ground="|=|  |=|  |=|  "),
    dict(id="z8", name="마이그레이션 사막", short="사막", lvl=64, base=64, color="#D4D6D8",
         normals=["schemaworm", "nullmirage", "scorpion", "norollback"], mini="fkcactus", boss="bigbang",
         desc="스키마가 모래처럼 흘러내리는 사막. 롤백 스크립트는 신기루다.", ground=".:. ..:. .:.. :."),
    dict(id="z9", name="보안 감사 요새", short="요새", lvl=74, base=74, color="#A5AAAE",
         normals=["hardcoded", "certknight", "phishmermaid", "cveskeleton"], mini="sqli", boss="auditgolem",
         desc="모든 요청이 세 번씩 검사받는 요새. 비밀번호 37개가 숨어 있다.", ground="#_#_#_#_#_#_#_#_"),
    dict(id="z10", name="할루시네이션 늪", short="늪", lvl=82, base=82, color="#95D85A",
         normals=["fakeapi", "fakecite", "confidentfrog", "tokenleech"], mini="siren", boss="temphydra",
         desc="자신만만한 목소리가 존재하지 않는 API를 알려 주는 늪.", ground="~.~ ?~.~ ~?.~ ~."),
    dict(id="z11", name="모노레포 대협곡", short="대협곡", lvl=90, base=90, color="#B8CEE0",
         normals=["cachebat", "codeowners", "difftroll", "flakymatrix"], mini="lockdragon", boss="build47",
         desc="한 저장소에 백 개의 서비스가 사는 협곡. 빌드는 평균 47분.", ground="/\\  /\\/\\   /\\  "),
    dict(id="z12", name="메인 브랜치 성", short="메인 브랜치", lvl=98, base=98, color="#F2F2F3",
         normals=["forcepush", "rebasewraith", "unsigned", "todolegion"], mini="revertrevert", boss="freezewarden",
         desc="모든 커밋이 흘러드는 성. 성벽에 수만 개의 TODO가 새겨져 있다.", ground="=|=|=|=|=|=|=|=|"),
]
FLOORS_PER_ZONE = 10
MINI_FLOOR, BOSS_FLOOR = 5, 10

# ============================================================== 아이템
# kind: food / drink / med / battle / special / mat / weapon / armor / acc / deco
# rarity: 0 일반 1 희귀 2 영웅 3 전설
RARITY = [("일반", "#A5AAAE"), ("희귀", "#75A1C7"), ("영웅", "#95D85A"), ("전설", "#6ABA23")]


def _i(name, kind, price, rarity=0, lvl=1, desc="", shop=True, **eff):
    return dict(name=name, kind=kind, price=price, rarity=rarity, lvl=lvl, desc=desc, shop=shop, eff=eff)


ITEMS = {
    # --- 음식 (full 포만, mood 기분, energy 체력, health 건강, kb 몸무게, bug 버그 생길 확률)
    "samgak": _i("삼각김밥", "food", 12, desc="편의점의 친구. 참치마요가 진리.", full=18, mood=2, kb=0.15),
    "kimbap": _i("김밥", "food", 20, desc="든든한 한 줄.", full=30, mood=4, kb=0.2),
    "ramen": _i("컵라면", "food", 15, desc="야근의 맛. 건강엔 별로.", full=26, mood=6, health=-2, kb=0.3, bug=0.1),
    "tteok": _i("떡볶이", "food", 35, desc="매콤달콤. 기분이 확 좋아진다.", full=35, mood=12, health=-2, kb=0.35),
    "salad": _i("샐러드", "food", 30, desc="건강해지는 맛… 이라고 한다.", full=18, mood=-3, health=10, kb=-0.2),
    "chicken": _i("치킨", "food", 60, lvl=3, desc="치킨은 진리다. 반반 무 많이.", full=55, mood=18, health=-3, kb=0.8, bug=0.2),
    "cake": _i("조각 케이크", "food", 45, lvl=2, desc="배포 성공 기념 케이크.", full=12, mood=25, kb=0.5),
    "tokenjelly": _i("토큰 젤리", "food", 0, rarity=1, shop=False, desc="토큰을 굳혀 만든 젤리. 경험치가 오른다.", full=20, mood=10, exp=25),
    # 시즌 한정 (시즌 중에만 상점에 나옴)
    "songpyeon": _i("송편", "food", 25, rarity=1, shop=False, desc="추석 한정. 예쁘게 빚으면 예쁜 코드가 나온대요.", full=25, mood=20, exp=10),
    "tteokguk": _i("떡국", "food", 30, rarity=1, shop=False, desc="설날 한정. 먹으면 한 살(?) 더 먹는다.", full=40, mood=15, exp=20),
    "xmascake": _i("크리스마스 케이크", "food", 50, rarity=1, shop=False, desc="크리스마스 한정. 산타도 배포는 안 한다.", full=20, mood=35),
    "candy": _i("호박 사탕", "food", 15, rarity=1, shop=False, desc="할로윈 한정. Trick or Treat or Merge?", full=8, mood=18),
    "pepero": _i("빼빼로", "food", 15, rarity=1, shop=False, desc="11월 11일 한정. 1과 1과 1과 1. 이진수 같다.", full=10, mood=20),
    # --- 음료
    "coffee": _i("아메리카노", "drink", 10, desc="개발자의 연료. 전투 중엔 HP 35% 회복.", energy=22, mood=2, full=2, hp_pct=0.35),
    "energydrink": _i("에너지드링크", "drink", 25, desc="날개를 달아준다(?). 전투 중엔 MP 회복.", energy=45, health=-4, mp_pct=0.45),
    "smoothie": _i("딸기 스무디", "drink", 30, desc="분홍색이라 기분이 좋다.", energy=15, health=5, mood=6),
    # --- 약
    "painkiller": _i("두통약", "med", 30, desc="스택트레이스를 너무 오래 봤을 때.", health=20, cure=["cold"]),
    "coldmed": _i("종합감기약", "med", 40, desc="콜록콜록 감기에 직빵.", health=12, cure=["cold"]),
    "vitamin": _i("비타민", "med", 25, desc="건강 +12. 전투 중엔 버그 감염 해제.", health=12, cure=["poison"]),
    "digestive": _i("소화제", "med", 20, desc="과식했을 때 한 알.", mood=5, cure=["overfed"]),
    "vacation": _i("휴가 쿠폰", "med", 150, lvl=1, rarity=1, desc="연차 사용! 번아웃 완치 + 체력/기분 대폭 회복.",
                   energy=60, mood=35, health=40, cure=["burnout", "cold"]),
    # --- 전투용
    "hotfixpatch": _i("핫픽스 패치", "battle", 40, lvl=3, desc="전투 중 HP 60% 회복.", hp_pct=0.6),
    "cacheflush": _i("캐시 플러시", "battle", 40, lvl=3, desc="전투 중 MP 60% 회복.", mp_pct=0.6),
    "rmrf": _i("rm -rf 폭탄", "battle", 80, lvl=6, rarity=1, desc="전투 중 적에게 고정 피해 (레벨 비례).", bomb=1),
    "firewall": _i("방화벽", "battle", 50, lvl=5, desc="전투 중 3턴간 방어력 x1.6.", buff="def_up"),
    # --- 특수
    "duck_charm": _i("축복받은 러버덕", "special", 0, rarity=2, shop=False, desc="강화 실패 시 등급 하락을 한 번 막아준다."),
    "exp_boost": _i("야근 수당", "special", 220, lvl=4, rarity=1, desc="30분간 경험치 2배."),
    "nametag": _i("이름표", "special", 60, desc="펫 이름을 바꿀 수 있다. (도감 > 설정)"),
    # --- 재료
    "shard_scan": _i("탐색의 파편", "mat", 0, shop=False, desc="read/grep/glob 도구가 남긴 조각. 방어구 강화 재료."),
    "shard_edit": _i("편집의 파편", "mat", 0, shop=False, desc="edit/write 도구가 남긴 조각. 무기 강화 재료."),
    "shard_exec": _i("실행의 파편", "mat", 0, shop=False, desc="bash 도구가 남긴 조각. 장신구 강화 재료."),
    "shard_team": _i("협업의 파편", "mat", 0, rarity=1, shop=False, desc="서브에이전트가 남기고 간 조각."),
    "shard_web": _i("웹의 파편", "mat", 0, rarity=1, shop=False, desc="webfetch 도구가 남긴 조각."),
    "bug_shell": _i("버그 껍질", "mat", 0, shop=False, desc="청소한 버그가 남긴 껍질. 의외로 쓸모가 있다."),
    "boss_core": _i("보스 코어", "mat", 0, rarity=2, shop=False, desc="보스가 떨어뜨린 핵. 고급 제작 재료."),
    "legacy_scroll": _i("레거시 두루마리", "mat", 0, rarity=1, shop=False, desc="아무도 못 읽는 문서. 가끔 전설 제작에 쓰인다."),
    # --- 무기: 키보드
    "kb_laptop": _i("노트북 키보드", "weapon", 0, shop=False, desc="기본 장비. 키감은 포기했다.", atk=1),
    "kb_membrane": _i("멤브레인 키보드", "weapon", 80, desc="사무실 기본템.", atk=3),
    "kb_brown": _i("갈축 기계식", "weapon", 300, lvl=5, rarity=1, desc="적당한 구분감.", atk=6),
    "kb_blue": _i("청축 기계식", "weapon", 350, lvl=6, rarity=1, desc="찰칵찰칵. 동료의 원성은 덤.", atk=8, luk=-1),
    "kb_red": _i("적축 기계식", "weapon", 380, lvl=8, rarity=1, desc="부드럽고 빠르다.", atk=7, spd=2),
    "kb_topre": _i("무접점 키보드", "weapon", 1200, lvl=14, rarity=2, desc="보글보글. 손가락이 행복하다.", atk=12, int=2),
    "kb_split": _i("스플릿 키보드", "weapon", 1300, lvl=16, rarity=2, desc="어깨가 펴진다.", atk=11, df=4),
    "kb_hhkb": _i("해피해킹 프로", "weapon", 0, lvl=22, rarity=3, shop=False, desc="Ctrl이 제자리에 있다.", atk=18, luk=4),
    "kb_modelm": _i("IBM 모델 M", "weapon", 0, lvl=24, rarity=3, shop=False, desc="1985년산. 둔기로도 쓸 수 있다.", atk=22, stun=0.1),
    "kb_ergodox": _i("에르고 스플릿 키보드", "weapon", 4200, lvl=40, rarity=2, desc="손목이 편해지고 타수가 오른다.", atk=27, df=3),
    "kb_optical": _i("광축 키보드", "weapon", 7800, lvl=55, rarity=2, desc="빛의 속도로 입력된다. 오타도 빛의 속도로.", atk=33, spd=4),
    "kb_green": _i("초록불 키보드", "weapon", 0, lvl=70, rarity=3, shop=False,
                   desc="마지막 초록 빌드의 빛으로 만든 키보드. 누르기만 해도 테스트가 통과할 것 같다.", atk=42, int=6, luk=4),
    # --- 방어구: 상의
    "hood_holed": _i("구멍난 후드티", "armor", 0, shop=False, desc="기본 장비. 소매가 늘어났다.", df=1),
    "hood_swag": _i("회사 굿즈 후드티", "armor", 90, desc="등에 회사 로고가 크게.", df=3),
    "hood_fleece": _i("기모 후드티", "armor", 350, lvl=6, rarity=1, desc="에어컨 빵빵한 사무실 필수.", df=6, hp=15),
    "flannel": _i("체크 남방", "armor", 450, lvl=10, rarity=1, desc="개발자 정장.", df=8, int=1),
    "vest": _i("판교 패딩 조끼", "armor", 1100, lvl=15, rarity=2, desc="IT 업계의 교복.", df=11, hp=30),
    "turtleneck": _i("검은 터틀넥", "armor", 1400, lvl=18, rarity=2, desc="발표할 때 입으면 설득력이 오른다.", df=10, int=5),
    "hood_armored": _i("방탄 후드티", "armor", 0, lvl=20, rarity=3, shop=False, desc="장애 대응도 버틴다.", df=18, hp=50),
    "cape": _i("망토형 담요", "armor", 0, lvl=24, rarity=3, shop=False, desc="사무실 의자에서 탄생한 전설.", df=14, luk=5),
    "hood_gore": _i("고어텍스 후드", "armor", 4500, lvl=40, rarity=2, desc="야근의 탑 꼭대기 바람도 막아 준다.", df=21, hp=70),
    "suit_oncall": _i("온콜 방호복", "armor", 8200, lvl=55, rarity=2, desc="새벽 3시 알림도 튕겨 낸다.", df=26, hp=110),
    "robe_senior": _i("시니어의 가운", "armor", 0, lvl=70, rarity=3, shop=False, desc="20년 치 TODO를 갚아 온 부엉이의 가운.", df=32, int=8, hp=120),
    # --- 장신구
    "monitorarm": _i("모니터암", "acc", 120, desc="목이 편해진다.", df=2, hp=10),
    "mug": _i("개발자 머그컵", "acc", 150, desc="'It works on my machine' 프린팅. 체력이 덜 닳는다.", energy_decay=0.8),
    "badge": _i("사원증", "acc", 200, desc="골드 획득 +10%.", gold=0.10),
    "sticker": _i("스티커 노트북", "acc", 350, lvl=4, rarity=1, desc="행운이 붙는다.", luk=5),
    "ergomouse": _i("버티컬 마우스", "acc", 400, lvl=8, rarity=1, desc="손목이 편해진다.", atk=2, spd=2),
    "duck": _i("러버덕", "acc", 0, rarity=1, shop=False, desc="설명하다 보면 답이 나온다.", int=3),
    "headphone": _i("노이즈캔슬링 헤드폰", "acc", 600, lvl=7, rarity=1, desc="집중력↑ 기분이 덜 떨어진다.", spd=3, mood_decay=0.7),
    "standing": _i("스탠딩 데스크", "acc", 900, lvl=12, rarity=2, desc="건강이 천천히 회복된다.", hp=25, regen=1),
    "crown": _i("해커톤 트로피", "acc", 0, rarity=3, shop=False, desc="모든 능력치 +3.", atk=3, df=3, int=3, spd=3, luk=3),
    "owl_feather": _i("부엉이 깃털 펜", "acc", 0, lvl=30, rarity=2, shop=False, desc="선배가 코드 리뷰에 쓰던 펜. 통찰이 생긴다.", int=6, luk=4),
    "lich_ring": _i("COBOL 인장 반지", "acc", 0, lvl=45, rarity=2, shop=False, desc="1987년부터 결제를 지켜 온 리치의 반지.", df=6, hp=60),
    "green_badge": _i("초록불 배지", "acc", 0, lvl=60, rarity=3, shop=False, desc="모든 빌드가 통과한 날의 기념 배지. 모든 능력치 +5.",
                      atk=5, df=5, int=5, spd=5, luk=5),
    # --- 방 꾸미기
    "plant": _i("몬스테라 화분", "deco", 60, desc="기분이 천천히 떨어진다.", mood_decay=0.9),
    "poster": _i("Ship it! 포스터", "deco", 80, desc="경험치 +5%.", exp=0.05),
    "fridge": _i("미니 냉장고", "deco", 200, lvl=3, desc="배가 천천히 꺼진다.", full_decay=0.8),
    "chair": _i("게이밍 의자", "deco", 300, lvl=4, desc="잘 때 체력 회복 +30%.", sleep_regen=1.3),
    "led": _i("RGB LED", "deco", 150, desc="기분이 30 밑으로 잘 안 떨어진다.", mood_floor=30),
    "dualmon": _i("듀얼 모니터", "deco", 400, lvl=6, rarity=1, desc="경험치 +5%, 전투 INT +2.", exp=0.05, int=2),
    "duckdoll": _i("대형 러버덕 인형", "deco", 250, lvl=5, desc="버그가 25% 덜 생긴다.", bug_rate=0.75),
    "aquarium": _i("버그 없는 어항", "deco", 350, lvl=8, rarity=1, desc="건강이 천천히 오른다.", regen=1),
    "serverrack": _i("홈서버 랙", "deco", 1500, lvl=20, rarity=2, desc="골드 +10%. 밤새 윙윙거린다.", gold=0.10),
    "greenlight": _i("초록불 트로피", "deco", 0, rarity=3, shop=False, desc="시즌 1 완결 기념. 경험치 +8%, 골드 +5%.", exp=0.08, gold=0.05),
}
EQUIP_SLOTS = {"weapon": "무기", "armor": "상의", "acc": "장신구"}
SLOT_SHARD = {"weapon": "shard_edit", "armor": "shard_scan", "acc": "shard_exec"}
MAX_PLACED_DECO = 4

# 방 꾸미기 그림 (2줄 이하)
DECO_ART = {
    "plant": [r" \|/ ", r" [_] "], "poster": [r"[SHIP]", r"[ IT!]"], "fridge": [r"[:::]", r"[___]"],
    "chair": [r" |\  ", r" |_\ "], "led": [r"~*~*~"], "dualmon": [r"[=][=]", r" /__\ "],
    "duckdoll": [r"  __ ", r"<(o )"], "aquarium": [r"[~><]", r"[~~~]"], "serverrack": [r"[||:]", r"[:||]"],
    "greenlight": [r"[ OK ]", r" \__/ "],
}

# 강화 (현재 +n → +n+1 성공 확률)
ENHANCE_RATES = [0.95, 0.90, 0.85, 0.70, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10]
ENHANCE_MAX = 10
ENHANCE_DOWNGRADE_FROM = 6   # +6 이상에서 실패하면 1단계 하락 (러버덕 부적으로 방지)

# 제작
RECIPES = {
    "r_energy": dict(out="energydrink", qty=2, need={"shard_exec": 3}, gold=0, lvl=1),
    "r_jelly": dict(out="tokenjelly", qty=1, need={"shard_scan": 2, "shard_edit": 2}, gold=0, lvl=1),
    "r_hotfix": dict(out="hotfixpatch", qty=2, need={"shard_exec": 2, "bug_shell": 3}, gold=0, lvl=3),
    "r_flush": dict(out="cacheflush", qty=2, need={"shard_web": 2, "shard_scan": 2}, gold=0, lvl=3),
    "r_duck": dict(out="duck", qty=1, need={"shard_scan": 6, "shard_team": 2}, gold=150, lvl=3),
    "r_charm": dict(out="duck_charm", qty=1, need={"bug_shell": 20, "shard_team": 3}, gold=200, lvl=5),
    "r_boost": dict(out="exp_boost", qty=1, need={"shard_team": 5, "shard_web": 3}, gold=100, lvl=4),
    "r_vacation": dict(out="vacation", qty=1, need={"boss_core": 1, "shard_team": 4}, gold=0, lvl=1),
    "r_headphone": dict(out="headphone", qty=1, need={"shard_web": 5, "shard_exec": 5}, gold=300, lvl=6),
    "r_topre": dict(out="kb_topre", qty=1, need={"shard_edit": 15, "boss_core": 1}, gold=800, lvl=12),
    "r_armored": dict(out="hood_armored", qty=1, need={"shard_scan": 15, "bug_shell": 30, "boss_core": 2}, gold=1500, lvl=20),
    "r_hhkb": dict(out="kb_hhkb", qty=1, need={"shard_edit": 30, "boss_core": 3, "shard_team": 10}, gold=3000, lvl=22),
    "r_cape": dict(out="cape", qty=1, need={"legacy_scroll": 5, "boss_core": 3, "shard_team": 8}, gold=2500, lvl=24),
    "r_modelm": dict(out="kb_modelm", qty=1, need={"legacy_scroll": 8, "boss_core": 4, "shard_edit": 25}, gold=4000, lvl=24),
    "r_ring": dict(out="lich_ring", qty=1, need={"legacy_scroll": 6, "boss_core": 3, "shard_scan": 20}, gold=3000, lvl=45),
    "r_robe": dict(out="robe_senior", qty=1, need={"legacy_scroll": 10, "boss_core": 6, "shard_team": 15}, gold=9000, lvl=68),
}

# 도구 → 파편
TOOL_SHARDS = {
    "read": "shard_scan", "grep": "shard_scan", "glob": "shard_scan", "list": "shard_scan", "ls": "shard_scan",
    "codesearch": "shard_scan", "lsp": "shard_scan", "todoread": "shard_scan",
    "edit": "shard_edit", "write": "shard_edit", "patch": "shard_edit", "multiedit": "shard_edit",
    "bash": "shard_exec", "task": "shard_team", "todowrite": "shard_team",
    "webfetch": "shard_web", "websearch": "shard_web", "fetch": "shard_web",
}

# 서브에이전트 → 동료
ALLIES = {
    "explore": dict(name="탐색 요정", color="#95D85A", art=[r" \o/ ", r"  ^  "]),
    "general": dict(name="범용 용병", color="#B8CEE0", art=[r" [o] ", r" /|\ "]),
    "build": dict(name="빌드 골렘", color="#3F77A6", art=[r" [#] ", r" | | "]),
    "plan": dict(name="기획 부엉이", color="#75A1C7", art=[r"{o,o}", r' "" ']),
    "_": dict(name="{agent} 소환수", color="#D4D6D8", art=[r" (*) ", r" /_\ "]),
}

# ============================================================== 던전 이벤트 (선택지)
# outcomes: [(확률, {효과}, 메시지)]
#   효과 키: gold exp hp_pct mp_pct energy mood full health bugs item(s) mat buff status fight ach int
EVENTS = [
    dict(id="friday", zone=2, text="금요일 오후 5시 59분. 누군가 배포 버튼을 켜둔 채 퇴근했다.",
         options=[("누른다 (Ship it!)", [(0.5, {"gold": 250, "exp": 60, "ach": "shipit"}, "배포 성공!! 아무 일도 없었다. 전설이 되었다."),
                                         (0.5, {"fight": "friday"}, "…장애 알림이 울린다. 드래곤이 나타났다!")]),
                  ("못 본 척 퇴근한다", [(1.0, {"mood": 8}, "현명한 선택. 주말이 평화로웠다.")])]),
    dict(id="so", zone=1, text="스택오버플로우 현자가 나타났다. '그 질문은 중복입니다.'",
         options=[("공손하게 부탁한다", [(0.6, {"buff": "focus", "exp": 20}, "현자가 답을 알려줬다! 집중력 상승."),
                                        (0.4, {"mood": -8}, "'closed as duplicate'… 마음이 아프다.")]),
                  ("직접 찾아본다", [(0.7, {"exp": 35}, "삽질 끝에 답을 찾았다! 경험치 획득."),
                                    (0.3, {"int": 1, "exp": 20}, "문서를 끝까지 읽었다! 지능이 영구히 +1.")])]),
    dict(id="ci", zone=1, text="CI 파이프라인에 빨간불이 들어왔다.",
         options=[("직접 고친다", [(1.0, {"energy": -10, "exp": 40}, "로그를 뒤져 고쳤다. 뿌듯하다.")]),
                  ("재실행 버튼 연타", [(0.5, {"gold": 60}, "…초록불이 됐다. 원인은 영원한 미스터리."),
                                       (0.5, {"bugs": 2, "mood": -5}, "빨간불이 번졌다. 버그가 따라왔다.")])]),
    dict(id="npm", zone=2, text="수상한 npm 패키지를 발견했다: 'left-pad-2-final-real'",
         options=[("설치해본다", [(0.65, {"items": 1}, "쓸만한 게 들어 있었다!"),
                                 (0.35, {"status": "poison", "bugs": 1}, "postinstall 스크립트가 버그를 뿌렸다!")]),
                  ("무시한다", [(1.0, {"exp": 10}, "보안 의식 +1.")])]),
    dict(id="simple", zone=1, text="누군가 다가와 '진짜 간단한 수정'이라며 부탁한다.",
         options=[("수락한다", [(0.7, {"energy": -15, "gold": 120}, "…간단하지 않았지만 보수는 두둑했다."),
                               (0.3, {"energy": -25, "mood": -10, "gold": 40}, "간단한 수정은 없다는 걸 다시 배웠다.")]),
                  ("정중히 거절한다", [(1.0, {"mood": -3, "exp": 15}, "거절도 기술이다.")])]),
    dict(id="duck", zone=1, text="길가의 러버덕이 말을 걸어왔다. '문제를 설명해 볼래?'",
         options=[("설명한다", [(1.0, {"hp_pct": 0.3, "cure": 1, "mood": 5}, "설명하다가 스스로 답을 찾았다! HP 회복.")]),
                  ("오리를 가방에 넣는다", [(0.3, {"item": "duck"}, "러버덕을 얻었다!"),
                                         (0.7, {"mood": -2}, "오리가 꽥 하고 도망갔다.")])]),
    dict(id="pizza", zone=1, text="'무료 피자 제공' 기술 세미나 알림이 떴다.",
         options=[("참석한다", [(1.0, {"full": 35, "energy": -8, "exp": 25}, "피자도 먹고 지식도 얻었다.")]),
                  ("일한다", [(1.0, {"gold": 40}, "성실함에 보너스가 나왔다.")])]),
    dict(id="comment", zone=3, text="레거시 코드에 주석이 딱 하나 있다: '// 절대 건드리지 마시오'",
         options=[("건드린다", [(0.3, {"mat": ("legacy_scroll", 2), "exp": 50}, "숨겨진 두루마리를 발견했다!"),
                               (0.7, {"status": "curse", "bugs": 2}, "…건드리지 말았어야 했다. 저주에 걸렸다.")]),
                  ("안 건드린다", [(1.0, {"exp": 15}, "현명하다. 선배들의 지혜를 존중했다.")])]),
    dict(id="zip", zone=2, text="보물상자처럼 생긴 'final_final_v3.zip'을 발견했다.",
         options=[("압축을 푼다", [(0.75, {"gold": 90, "items": 1}, "안에 골드와 아이템이 들어 있었다!"),
                                  (0.25, {"fight": "mimic"}, "미믹이었다!")]),
                  ("지나간다", [(1.0, {}, "zip 폭탄일지도 몰랐다.")])]),
    dict(id="coffeemachine", zone=1, text="휴게실에서 반짝이는 커피 머신을 발견했다.",
         options=[("한 잔 마신다", [(1.0, {"energy": 25, "hp_pct": 0.2}, "카페인이 온몸에 퍼진다!")]),
                  ("원두를 챙긴다", [(1.0, {"item": "coffee"}, "아메리카노를 얻었다.")])]),
    dict(id="oncall", zone=4, text="새벽 3시, 온콜 호출이 울렸다.",
         options=[("받는다", [(0.6, {"gold": 200, "energy": -20, "exp": 60}, "장애를 막아냈다! 온콜 수당 획득."),
                             (0.4, {"fight": "errdragon"}, "장애가 커졌다. 드래곤이 깨어났다!")]),
                  ("못 들은 척한다", [(1.0, {"mood": -12}, "죄책감에 잠을 설쳤다.")])]),
    dict(id="refactor", zone=3, text="'이참에 전부 리팩터링하자'는 유혹이 속삭인다.",
         options=[("전부 갈아엎는다", [(0.4, {"exp": 120, "gold": 50}, "기적적으로 성공했다! 코드가 반짝인다."),
                                     (0.6, {"energy": -25, "bugs": 3}, "3주가 지났다. 아직 반도 못 했다.")]),
                  ("조금씩 개선한다", [(1.0, {"exp": 40}, "보이스카우트 규칙: 왔을 때보다 깨끗하게.")])]),
    dict(id="standup", zone=5, text="15분짜리 스탠드업이 45분째 이어지고 있다.",
         options=[("끝까지 듣는다", [(1.0, {"energy": -12, "mood": -5, "exp": 20}, "…무언가를 배운 것 같기도.")]),
                  ("'다음에 따로 얘기하시죠'", [(0.7, {"mood": 10}, "회의가 끝났다! 모두가 당신을 존경한다."),
                                            (0.3, {"fight": "meeting"}, "회의가 살아 움직이기 시작했다!")])]),
    dict(id="billing", zone=6, text="클라우드 콘솔에 '예상 청구액'이 빨갛게 떠 있다.",
         options=[("리소스를 정리한다", [(1.0, {"gold": 150, "exp": 40}, "안 쓰는 인스턴스 37개를 지웠다. 절약!")]),
                  ("못 본 척한다", [(0.5, {}, "다음 달의 내가 해결하겠지."),
                                   (0.5, {"fight": "billing"}, "청구서가 골렘이 되어 덮쳐왔다!")])]),
    # --- 스토리 후반 지역 (야근의 탑 ~ 메인 브랜치 성)
    dict(id="justthis", zone=7, text="퇴근 30분 전, '잠깐 이것만 봐 주실 수 있어요?' 메시지가 도착했다.",
         options=[("이것만 본다", [(0.6, {"gold": 320, "energy": -18, "exp": 160}, "정말 이것만이었다! 기적이다."),
                                  (0.4, {"fight": "hotfixzombie"}, "이것만이 아니었다. 핫픽스 좀비가 일어났다!")]),
                  ("'내일 오전에 볼게요'", [(1.0, {"mood": 10, "energy": 8}, "정시 퇴근. 내일의 내가 힘내겠지.")])]),
    dict(id="backuptape", zone=8, text="모래 속에서 백업 테이프를 발견했다. 라벨: 'final_really_final'",
         options=[("복원해 본다", [(0.5, {"mat": ("legacy_scroll", 2), "exp": 180}, "복원 성공! 잃어버린 두루마리가 나왔다."),
                                  (0.5, {"bugs": 3, "status": "curse"}, "…2017년의 스키마가 튀어나왔다. 저주에 걸렸다.")]),
                  ("그냥 묻어 둔다", [(1.0, {"exp": 40}, "어떤 과거는 묻어 두는 게 낫다.")])]),
    dict(id="phishmail", zone=9, text="'[긴급] 비밀번호가 만료되었습니다. 여기를 누르세요' 메일이 왔다.",
         options=[("링크를 누른다", [(1.0, {"fight": "phishmermaid"}, "…인어가 노래하며 튀어나왔다!")]),
                  ("보안팀에 신고한다", [(1.0, {"exp": 200, "gold": 150}, "훈련용 메일이었다! 보안 의식 +1, 포상금 획득.")])]),
    dict(id="sure", zone=10, text="늪 위에 '100% 정확한 지름길'이라고 적힌 표지판이 서 있다.",
         options=[("믿고 따라간다", [(0.4, {"items": 2}, "…정말 지름길이었다. 이번엔."),
                                    (0.6, {"fight": "confidentfrog"}, "표지판을 세운 건 개구리였다!")]),
                  ("공식 문서를 확인한다", [(0.7, {"exp": 200}, "문서엔 다른 길이 있었다. 역시 문서."),
                                          (0.3, {"exp": 120, "int": 1}, "문서를 끝까지 읽었다! 지능이 영구히 +1.")])]),
    dict(id="build47", zone=11, text="빌드가 47분째 돌고 있다. 할 일이 없다.",
         options=[("커피를 타러 간다", [(1.0, {"energy": 25, "mood": 8}, "돌아오니 아직 23%. 커피가 맛있다.")]),
                  ("로컬에서 먼저 돌려 본다", [(0.6, {"exp": 260}, "로컬에서 버그를 먼저 찾았다! 시간 절약."),
                                              (0.4, {"fight": "flakymatrix"}, "로컬에선 통과, CI에선 실패. 매트릭스가 깨어났다!")])]),
    dict(id="fridaygate", zone=12, text="성문에 '금요일 배포 금지'라고 적혀 있다. 오늘은 금요일이다.",
         options=[("그래도 배포한다", [(0.5, {"gold": 900, "exp": 400, "ach": "shipit"}, "아무 일도 없었다. 성벽이 박수를 쳤다."),
                                      (0.5, {"fight": "friday"}, "…역시. 금요일 드래곤이 나타났다!")]),
                  ("월요일에 한다", [(1.0, {"mood": 12, "exp": 80}, "현명하다. 주말이 평화로웠다.")])]),
]

# ============================================================== 미니게임
TYPING_PHRASES = [
    "git commit -m 'fix'", "git push origin main", "npm install", "SELECT * FROM users;", "console.log('why')",
    "print('hello world')", "docker compose up -d", "kubectl get pods", "def main():", "return None",
    "if err != nil {", "for i in range(10):", "rm -rf node_modules", "git rebase -i HEAD~3", "pip install -r req.txt",
    "배포는 금요일에 하지 않는다", "테스트 코드는 미래의 나를 위한 편지", "주석은 코드의 일기장", "오늘도 무사히 퇴근",
    "탭과 스페이스는 싸우지 않는다", "레거시를 존중하라", "커밋 메시지는 성의 있게", "로컬에서는 잘 됐는데",
]
MINIGAMES = [
    ("dir", "방향 맞히기", "고개를 돌릴 방향을 맞혀요 (←/→)"),
    ("whack", "버그 잡기", "튀어나오는 버그를 숫자키로 잡아요 (20초)"),
    ("type", "타자 연습", "개발자 문장 3개를 빠르고 정확하게"),
    ("quiz", "개발 퀴즈 O/X", "개발 상식 5문제! O 또는 X (문제당 12초)"),
]
QUIZ_TIME = 12.0
# (문제, 정답(O=True), 해설)
QUIZ = [
    ("HTTP 404는 '서버 내부 오류'라는 뜻이다", False, "404는 Not Found. 서버 내부 오류는 500이에요"),
    ("HTTP 429는 'Too Many Requests'(요청 과다)다", True, "던전의 그 드래곤이 바로 429예요"),
    ("HTTPS의 기본 포트는 443이다", True, "HTTP는 80, HTTPS는 443"),
    ("HTTP 301은 '영구 이동(Moved Permanently)'이다", True, "302는 임시 이동(Found)"),
    ("HTTP 헤더 이름은 대소문자를 구분한다", False, "헤더 이름은 대소문자를 구분하지 않아요"),
    ("HTTP GET 요청은 멱등(idempotent)해야 한다", True, "같은 GET을 여러 번 보내도 서버 상태가 같아야 해요"),
    ("REST에서 PUT은 전체 교체, PATCH는 부분 수정에 주로 쓴다", True, "관례적으로 그렇게 나눠 써요"),
    ("JSON은 주석(// 또는 /* */)을 공식적으로 지원한다", False, "표준 JSON엔 주석이 없어요 (JSONC/JSON5는 별개)"),
    ("JavaScript에서 typeof null의 결과는 'object'다", True, "초창기 버그가 호환성 때문에 그대로 남았어요"),
    ("JavaScript에서 NaN === NaN은 true다", False, "NaN은 자기 자신과도 같지 않아요. Number.isNaN()을 쓰세요"),
    ("JavaScript의 ==는 타입 변환 없이 비교한다", False, "==는 타입을 바꿔서 비교해요. 그대로 비교하려면 ==="),
    ("JavaScript에서 const로 선언한 배열에도 push는 할 수 있다", True, "const는 재할당만 막아요. 내용 변경은 가능"),
    ("0.1 + 0.2 == 0.3 은 대부분의 언어에서 참(true)이다", False, "부동소수점 오차로 0.30000000000000004가 돼요"),
    ("Python의 is 연산자는 두 값이 같은 '값'인지 비교한다", False, "is는 같은 객체인지 봐요. 값 비교는 =="),
    ("Python의 range(5)에는 5가 포함된다", False, "0, 1, 2, 3, 4까지예요"),
    ("Python 3.7부터 dict는 넣은 순서를 보장한다", True, "3.7부터 언어 사양으로 보장돼요"),
    ("Python의 튜플은 변경 불가능(immutable)하다", True, "리스트와 달리 요소를 바꿀 수 없어요"),
    ("Python에서 def f(a=[])의 기본값 리스트는 호출할 때마다 새로 만들어진다", False,
     "정의할 때 한 번만 만들어져 공유돼요. 기본값은 None으로!"),
    ("Python f-string(f\"{x}\")은 3.6부터 쓸 수 있다", True, "3.6에서 들어온 문법이에요"),
    ("SQL에서 NULL = NULL 의 결과는 TRUE다", False, "NULL 비교는 UNKNOWN이에요. IS NULL을 쓰세요"),
    ("SQL의 COUNT(*)는 NULL이 들어 있는 행은 세지 않는다", False, "COUNT(*)는 모든 행을 세요. NULL을 빼는 건 COUNT(컬럼)"),
    ("LEFT JOIN은 오른쪽 테이블에 짝이 없으면 왼쪽 행도 버린다", False, "왼쪽 행은 남고 오른쪽 컬럼이 NULL로 채워져요"),
    ("인덱스를 추가하면 INSERT도 항상 빨라진다", False, "인덱스도 같이 고쳐야 해서 쓰기는 보통 느려져요"),
    ("git pull은 fetch 한 뒤 merge(또는 rebase)를 하는 것이다", True, "가져오기 + 합치기 한 방"),
    ("git rebase를 하면 커밋 해시가 바뀔 수 있다", True, "커밋을 새로 만들기 때문에 해시가 달라져요"),
    ("git reset --hard는 작업 디렉터리의 변경 사항도 버린다", True, "커밋 안 한 변경은 되돌릴 수 없어요 (커밋은 reflog로 복구)"),
    ("git stash는 커밋하지 않은 변경을 임시로 치워 둔다", True, "git stash pop으로 다시 꺼내요"),
    ("HEAD~1은 현재 커밋의 바로 이전(부모) 커밋을 가리킨다", True, "HEAD~2는 두 단계 전"),
    ("스택은 FIFO, 큐는 LIFO 구조다", False, "반대예요. 스택은 LIFO(후입선출), 큐는 FIFO(선입선출)"),
    ("정렬된 배열에서 이진 탐색은 O(log n)이다", True, "반씩 줄여 나가니까요"),
    ("퀵 정렬의 최악 시간 복잡도는 O(n²)이다", True, "피벗 운이 나쁘면요. 평균은 O(n log n)"),
    ("좋은 해시 함수를 쓰면 해시 충돌은 절대 일어나지 않는다", False, "가능한 입력이 출력보다 많으면 충돌은 피할 수 없어요"),
    ("TCP는 순서를 보장하지 않고, UDP는 순서를 보장한다", False, "반대예요. 순서·재전송을 보장하는 건 TCP"),
    ("IPv4 주소는 32비트다", True, "IPv6는 128비트"),
    ("localhost는 보통 127.0.0.1을 가리킨다", True, "루프백 주소. '로컬에선 잘 되는데'의 그곳"),
    ("UTF-8에서 한글 한 글자(가~힣)는 3바이트다", True, "한글 음절은 UTF-8로 3바이트예요"),
    ("리눅스에서 chmod 755는 소유자에게 쓰기 권한을 준다", True, "7=rwx(소유자), 5=r-x(그룹/그 외)"),
    ("ls -a는 이름이 .으로 시작하는 숨김 파일도 보여준다", True, "-a = all"),
    ("cron 표현식 '0 9 * * 1'은 매주 월요일 오전 9시다", True, "분 시 일 월 요일 순서. 1 = 월요일"),
    ("정규식 .*는 기본적으로 게으른(lazy) 매칭을 한다", False, "기본은 탐욕적(greedy). 게으르게 하려면 .*?"),
    ("YAML은 들여쓰기에 탭 문자를 쓸 수 없다", True, "YAML 들여쓰기는 스페이스만 돼요"),
    ("Rust는 가비지 컬렉터로 메모리를 관리한다", False, "소유권(ownership)과 빌림 규칙으로 관리해요"),
    ("docker rm으로 컨테이너를 지워도 이름 있는 볼륨의 데이터는 남는다", True, "볼륨은 docker volume rm으로 따로 지워요"),
    ("LLM의 토큰 1개는 항상 단어 1개와 같다", False, "토큰은 단어보다 작은 조각일 때가 많아요. 한글은 더 잘게 쪼개지기도"),
    ("대화가 길어지면 opencode는 컨텍스트를 압축(compact)할 수 있다", True, "오래된 대화를 요약해서 토큰을 아껴요"),
    ("CSS z-index는 position: static인 요소에도 항상 적용된다", False, "static에선 무시돼요 (flex/grid 자식은 예외)"),
    ("1바이트는 8비트다", True, "그래서 토큰펫 '바이트'는 비트 8개가 모여서 태어났어요"),
    ("DNS는 도메인 이름을 IP 주소로 바꿔준다", True, "인터넷의 전화번호부"),
    ("'It works on my machine'은 공식 품질 인증 마크다", False, "…였으면 좋겠지만 아니에요"),
    ("금요일 오후 배포는 업계 모범 사례(best practice)다", False, "금요일 배포 드래곤이 기다리고 있어요"),
]
# 버그잡기 칸 배치 (숫자패드)
WHACK_LAYOUT = [["7", "8", "9"], ["4", "5", "6"], ["1", "2", "3"]]

# ============================================================== 업적
# (id, 이름, 설명, 보상 골드, 칭호)
ACHIEVEMENTS = [
    ("hatch", "부화 성공", "알에서 깨어나기", 50, "신생아"),
    ("evolve2", "무럭무럭", "유년기로 진화", 100, None),
    ("evolve3", "질풍노도", "청소년기로 진화", 200, None),
    ("evolve4", "어엿한 성체", "성체로 진화", 500, "어른"),
    ("evolve5", "특이점 도달", "전설로 진화", 3000, "특이점"),
    ("meal50", "먹방 유튜버", "밥 50번 먹기", 150, "먹방러"),
    ("tokens1m", "백만 토큰 먹방", "토큰 100만 개 먹기", 500, "토큰 미식가"),
    ("tokens10m", "토큰 블랙홀", "토큰 1,000만 개 먹기", 2000, "토큰 블랙홀"),
    ("clean50", "버그 청소부", "버그 50마리 청소", 200, "청소부"),
    ("clean300", "방역 전문가", "버그 300마리 청소", 800, "방역 전문가"),
    ("kill100", "몬스터 백 마리", "몬스터 100마리 처치", 300, None),
    ("kill1000", "천하무적 디버거", "몬스터 1,000마리 처치", 1500, "디버거"),
    ("boss429", "레이트리밋 슬레이어", "429 레이트리밋 드래곤 격파", 500, "429 슬레이어"),
    ("friday", "금요일 배포 생존자", "금요일 배포 드래곤 격파", 300, "금배 생존자"),
    ("zone_z1", "로컬호스트 정복", "로컬호스트 평원 보스 격파", 150, None),
    ("zone_z2", "의존성 지옥 탈출", "node_modules 심연 보스 격파", 300, "npm 생존자"),
    ("zone_z3", "레거시 퇴마사", "레거시 코드 무덤 보스 격파", 500, "퇴마사"),
    ("zone_z4", "프로덕션 수호자", "프로덕션 서버실 보스 격파", 800, "수호자"),
    ("zone_z5", "회의실 탈출", "회의실 미궁 보스 격파", 1200, "탈출 장인"),
    ("zone_z6", "클라우드 정복자", "클라우드 성층권 보스 격파", 2000, "클라우드 정복자"),
    ("enh7", "강화의 신", "장비 +7 달성", 500, "강화의 신"),
    ("enh10", "+10 장인", "장비 +10 달성", 3000, "+10 장인"),
    ("enhfail5", "멘탈 강화", "강화 5연속 실패", 300, "멘탈 갑"),
    ("night", "새벽 코더", "새벽 2~5시에 AI 일 시키기", 200, "올빼미"),
    ("quests10", "응답 수집가", "응답 10번 받기", 100, None),
    ("quests100", "프롬프트 장인", "응답 100번 받기", 800, "프롬프트 장인"),
    ("perfect_type", "타자왕", "타자 연습 정확도 100% + 분당 200타 이상", 300, "타자왕"),
    ("whack20", "버그 잡기 달인", "버그 잡기 한 판에 20마리", 300, "버그잡이"),
    ("streak7", "개근상", "7일 연속 출근 도장", 700, "개근"),
    ("rich10k", "골드 부자", "골드 10,000 보유", 500, "금수저"),
    ("burnout", "번아웃 극복", "번아웃에서 회복", 300, "불사조"),
    ("allies50", "팀 플레이어", "서브에이전트 동료 50번 합류", 500, "팀장"),
    ("longprompt", "장문의 지시자", "2,000자 넘는 요청 보내기", 200, "기획자"),
    ("careful", "모범 보호자", "돌봄 점수 90 이상으로 성체 진화", 600, "모범 보호자"),
    ("legacy", "선대 용사의 후예", "TOKEN QUEST v1 기록 계승", 200, "후예"),
    ("dex_all", "도감 완성", "모든 몬스터 처치", 2000, "수집가"),
    ("shipit", "Ship it!", "배포 이벤트 성공", 200, None),
    ("craft10", "공방 단골", "아이템 10번 제작", 300, "장인"),
    ("deco4", "인테리어 장인", "꾸미기 4개 배치", 200, "인테리어 장인"),
    ("holiday", "명절에도 코딩", "명절/공휴일 이벤트 기간에 AI 일 시키기", 300, "워커홀릭"),
    ("diary7", "꼬박꼬박 일기", "개발 일지 7일치 모으기", 300, None),
    ("friends", "친구가 놀러왔어요", "다른 인스턴스의 펫이 놀러오기", 150, "인싸"),
    ("anniv", "N주 기념일", "부화 후 7일 기념일 맞이하기", 300, None),
    # --- v3
    ("todo100", "체크리스트 마스터", "opencode 할 일 100개 완료", 500, "체크리스트 마스터"),
    ("todolist10", "완주의 기쁨", "할 일 목록 10개를 끝까지 완료", 400, None),
    ("fastperm", "빠른 결재", "opencode 허락 요청에 15초 안에 응답", 150, "결재왕"),
    ("compact10", "소화 기관", "컨텍스트 압축 10번 지켜보기", 200, "소화왕"),
    ("scold10", "엄한 보호자", "떼쓰기를 10번 훈육", 250, "호랑이 선생님"),
    ("discipline100", "모범생", "훈육 게이지 100 달성", 400, "모범생"),
    ("quiz_perfect", "개발 상식왕", "개발 퀴즈 5문제 모두 정답", 300, "상식왕"),
    ("retire", "명예의 전당", "펫을 은퇴시켜 명예의 전당에 올리기", 1000, "명예로운 보호자"),
    ("gen3", "3대째 개발자 가문", "3세대 펫 키우기", 800, "명문가"),
    ("forms6", "진화 도감 수집가", "성체 6종 모두 만나기 (세대 누적)", 2000, "진화 박사"),
    ("raid_clear", "레이드 공대원", "주간 레이드 보스 격파에 기여", 500, "공대원"),
    ("raid_mvp", "레이드 MVP", "주간 레이드 기여 1위", 800, "MVP"),
    ("maintainer", "오픈소스의 수호자", "비밀 전설 형태로 진화", 3000, "메인테이너"),
    # --- v4 메인 스토리
    ("zone_z7", "칼퇴의 전설", "야근의 탑 보스 격파", 2500, "칼퇴 요정"),
    ("zone_z8", "사막 횡단", "마이그레이션 사막 보스 격파", 3000, "마이그레이터"),
    ("zone_z9", "감사 통과", "보안 감사 요새 보스 격파", 3500, "화이트 해커"),
    ("zone_z10", "팩트 체커", "할루시네이션 늪 보스 격파", 4000, "팩트 체커"),
    ("zone_z11", "머지 마스터", "모노레포 대협곡 보스 격파", 4500, "머지 마스터"),
    ("zone_z12", "메인 브랜치 입성", "메인 브랜치 성 보스 격파", 5000, "메인테이너 후보"),
    ("story_ch3", "초록불 추적자", "스토리 3장 완료", 500, "추적자"),
    ("story_ch6", "구름 너머로", "스토리 6장 완료", 1500, "구름 위의 용사"),
    ("story_ch9", "요새 돌파", "스토리 9장 완료", 3000, None),
    ("season1", "초록불을 찾아서", "스토리 시즌 1 완결", 8000, "초록불의 수호자"),
    ("story_bonus", "보너스 사냥꾼", "스토리 보너스 미션 6개 달성", 1000, "완벽주의자"),
]

# ============================================================== 일일 퀘스트
# (id, 문구, 최소, 최대, 골드, 경험치)
DAILY_QUESTS = [
    ("resp", "응답 {n}번 받기", 3, 5, 80, 40),
    ("kill", "몬스터 {n}마리 처치", 8, 15, 100, 60),
    ("clean", "버그 {n}마리 청소", 3, 6, 60, 30),
    ("game", "미니게임 {n}판", 2, 3, 70, 40),
    ("feed", "밥 {n}번 주기", 2, 4, 50, 20),
    ("tokens", "토큰 {n}만 개 먹기", 3, 15, 90, 50),
    ("floor", "던전 {n}층 돌파", 3, 6, 90, 60),
    ("shard", "파편 {n}개 모으기", 8, 20, 70, 40),
    ("compose", "컴포즈로 {n}번 보내기", 1, 3, 60, 30),
    ("pat", "쓰다듬기 {n}번", 3, 6, 40, 20),
    ("todo", "opencode 할 일 {n}개 완료", 2, 6, 80, 40),
    ("quiz", "개발 퀴즈 {n}문제 맞히기", 3, 6, 60, 40),
    ("raid", "주간 레이드 {n}번 출격", 1, 2, 90, 50),
]

# ============================================================== 대사
LINES = {
    "idle": ["오늘도 커밋 화이팅!", "주인님 코드, 제 눈엔 완벽해요", "린트 경고는 못 본 걸로 할게요",
             "심심하면 저랑 놀아요! [P]", "방금 제 꼬리에서 NullPointer 났어요", "배포는 신중하게… 아시죠?",
             "저 요즘 타입스크립트 공부해요 (거짓말)", "탭 vs 스페이스… 저는 중립입니다",
             "주석 좀 달아주세요. 미래의 주인님을 위해서요", "세미콜론 하나에 인생이 바뀔 수 있어요",
             "오늘의 운세: 머지 컨플릭트 주의", "제 몸무게는 비밀이에요… {kb}KB", "LGTM 한 번만 해주세요",
             "rubber duck 말고 저한테 설명해도 돼요", "커피 한 잔 어때요?"],
    "hungry": ["배고파요… 토큰 한 입만…", "밥 안 주면 버그 싸버릴 거예요! [F]", "배에서 404 Not Found 소리가 나요",
               "김밥… 김밥이 보고 싶어요…", "허기져서 스택이 안 쌓여요"],
    "starving": ["배고파서 쓰러질 것 같아요… [F]", "…(꼬르륵) 메모리가 부족합니다…"],
    "sleepy": ["눈꺼풀이 git revert 되고 있어요…", "졸려요… sleep(28800) 해도 돼요? [Z]", "하품… 컴파일 기다리는 기분이에요"],
    "sleeping": ["zZ… 배포… 성공…", "zZ… 리팩터링… 하지 마…", "zZ… 테스트 초록불… 음냐…", "zZ… 429… 무서워…",
                 "zZ… 치킨 반반… 무 많이…"],
    "dirty": ["방에 버그가 너무 많아요! [C]", "여기가 제 방인지 레거시 코드인지…", "버그들이 저를 쳐다봐요…"],
    "sick": ["머리가 아파요… 스택트레이스가 보여요…", "콜록… 메모리 누수인가 봐요…", "약 주세요… [M]"],
    "overfed": ["배가 너무 불러요… 소화제… [M]", "과식했어요… 굴러다니는 중…"],
    "burnout": ["…(번아웃) 아무것도 하기 싫어요…", "휴가… 휴가가 필요해요… [M]"],
    "bored": ["심심해요… 놀아줘요! [P]", "버그 잡기 한 판 어때요? [P]", "AI도 쉬고 나도 쉬고… 심심…"],
    "happy": ["기분 최고! 오늘은 뭐든 배포할 수 있어요!", "주인님 최고!", "이 기세면 레거시도 안 무서워요!"],
    "busy": ["AI가 일하는 동안 저는 던전 다녀올게요!", "토큰 냄새… 맛있다…", "주인님, 이번엔 테스트도 부탁하셨죠?",
             "기다리는 동안 몬스터나 잡을게요", "AI 선배님 화이팅!"],
    "response": ["응답 왔어요! 코드 리뷰 해주실 거죠?", "퀘스트 완료! 보상 받았어요!", "다 됐대요! 바로 확인해 보세요!"],
    "error": ["으악! 에러다! 무서워요!", "빨간 글씨는 싫어요…", "괜찮아요, 에러는 성장의 증거랬어요"],
    "ratelimit": ["429래요… 좀 쉬었다 하래요", "쿨다운 중… 심호흡…"],
    "retry": ["다시 시도 중이래요… 두근두근", "재시도… 제발 한 번에…"],
    "night": ["벌써 새벽이에요. 커밋하고 자요…", "새벽 코딩은 버그를 부른대요", "지금 짠 코드, 내일 아침에 다시 봐요"],
    "morning": ["좋은 아침이에요! 오늘의 첫 커밋은?", "출근 도장 쾅! 오늘도 화이팅"],
    "monday": ["월요일이다… 배포 금지 요일은 아니지만 기분은 금지"],
    "friday": ["금요일엔 배포하지 마세요. 제발요.", "불금! …배포는 월요일에 해요"],
    "compose": ["명령 접수! 제가 AI한테 잘 말해둘게요", "오 이번 요청 멋진데요?", "주인님의 지시, 토큰으로 바꿔드리죠!",
                "좋아요, 기다리는 동안 던전 다녀올게요"],
    "compose_long": ["와 장문이다… 읽다가 잠들 뻔했어요", "이 정도면 거의 기획서예요!"],
    "compose_bug": ["버그 사냥 개시! 잠자리채 챙길게요", "버그요? 제 전문이에요!"],
    "compose_test": ["초록불 기원합니다!", "테스트는 미래의 주인님을 위한 편지!"],
    "compose_refactor": ["리팩터링! 제 기본기예요 (슬래시!)", "스파게티 썰러 가요!"],
    "compose_urgent": ["헉 급한 거예요?! 서둘러요!", "급할수록 돌아가래요… 근데 빨리요!"],
    "compose_thanks": ["천만에요! (제가 한 건 아니지만)", "칭찬은 토큰펫도 춤추게 해요!"],
    "compose_deploy": ["배포요?! 오늘 무슨 요일이죠…?", "배포 전에 테스트… 하셨죠?"],
    "eat": ["냠냠!", "맛있어요!", "토큰보다 맛있다…", "(우물우물)"],
    "eat_full": ["배불러요… 더는 못 먹어요", "과식했어요… 소화제…"],
    "clean": ["깨끗해졌다! 상쾌해요!", "버그 박멸 완료!"],
    "pat": ["헤헤… 좋아요", "더 쓰다듬어 주세요!", "(골골송)", "기분이 +1 되었습니다"],
    "play_win": ["이겼다! 한 판 더!", "제가 좀 하죠?"],
    "play_lose": ["다음엔 안 져요!", "봐준 거예요…"],
    "levelup": ["레벨 업! 야근 스킬이 올랐어요", "더 강해졌어요!"],
    "evolve": ["몸이… 몸이 컴파일되고 있어요!!"],
    "faint": ["으윽… 핫픽스가 필요해…"],
    "depart": ["다녀올게요! 전리품 기대하세요!", "던전 출발! AI 선배 일하는 동안!"],
    "return": ["다녀왔어요! 전리품 확인해 보세요!", "무사 귀환! (배고파요)"],
    "ally": ["{ally}이(가) 도와주러 왔어요!", "동료다! {ally} 고마워요!"],
    "welcome": ["보고 싶었어요!", "어디 갔다 오셨어요? 저 혼자 버그 잡았어요"],
    "rich": ["부자다! 치킨 사주세요!"],
    "poor": ["지갑이 텅 비었어요… 모험 가요"],
    "egg": ["(꿈틀)", "(톡톡)", "…(따뜻하다)", "(안에서 타자 소리가 난다)"],
    # --- v3
    "scold": ["…네. 알겠어요 (훌쩍)", "죄송해요… 다신 안 그럴게요", "(반성 중… git revert 하는 중)"],
    "scold_wrong": ["왜요?! 저 아무것도 안 했어요! (억울)", "억울해요… 가만히 있었는데…"],
    "tantrum": ["놀아줘놀아줘놀아줘!!", "싫어싫어! 지금 당장 놀아줘요!", "(바닥에 드러누워 버둥버둥)"],
    "spoiled": ["헤헤 역시 주인님은 제 편!", "(…떼쓰면 되는구나)"],
    "perm": ["주인님! opencode가 허락을 기다려요!", "결재 서류 올라왔어요! 확인해 주세요", "AI 선배가 '해도 돼요?' 하고 물어봐요"],
    "perm_fast": ["빛의 속도로 결재! 멋져요", "결재왕 주인님!"],
    "ask": ["AI 선배가 질문을 했어요! opencode 창 확인!", "선택지가 떴어요! 골라주세요"],
    "compacted": ["꺼억~ 컨텍스트 잘 먹었습니다 (압축)", "대화를 꼭꼭 씹어서 요약했어요!"],
    "abort": ["앗, 멈췄다! 방향 바꾸는 거죠?", "중단! …다시 생각해 보는 것도 좋아요"],
    "todo_done": ["할 일 하나 끝! 체크!", "체크 표시가 제일 좋아요", "하나 해치웠다!"],
    "todo_all": ["할 일 전부 완료!! 메인 퀘스트 클리어!", "체크리스트 올클리어! 오늘 칼퇴각?"],
    "todo_new": ["새 퀘스트 목록이 왔어요! {n}개!", "할 일이 {n}개래요. 같이 해치워요!"],
    "command": ["주문 시전! /{cmd}", "/{cmd}! 멋있는 명령어예요"],
    "raid": ["레이드 출격! 다 같이 쓰러뜨려요!", "주간 보스 잡으러 가요!"],
    "retire": ["그동안 고마웠어요, 주인님…", "명예의 전당에서 지켜볼게요!"],
    "quiz_win": ["상식왕 등극!", "이 정도는 기본이죠!"],
    # --- v4 스토리
    "story_new": ["새 챕터 신호가 잡혔어요! [7] 스토리", "커밋 조각 반응이 느껴져요! [7]", "부엉이 선배한테서 연락 왔어요! [7]"],
    "story_boss": ["챕터 보스 신호 포착! 준비되면 [7] → [B]", "조각이 바로 앞에 있어요! 보스만 넘으면 돼요"],
    "story_clear": ["커밋 조각 확보! 초록불이 조금 밝아졌어요", "한 조각 더! 세상의 빌드가 조금 초록해졌어요"],
}

# 호출(관심 요청) 종류
CALLS = {
    "hungry": ("배고파!", "F"), "dirty": ("청소해줘!", "C"), "sick": ("아파…", "M"),
    "sleepy": ("졸려…", "Z"), "play": ("놀아줘!", "P"), "pat": ("쓰다듬어줘!", "J"),
    "tantrum": ("떼쓰는 중!!", "G"),   # 필요한 건 다 채워졌는데 괜히 떼를 쓴다 → [G] 훈육이 정답
}


# ============================================================== 시즌 이벤트
# dates: [("MM-DD","MM-DD")] 매년 / [("YYYY-MM-DD","YYYY-MM-DD")] 특정 연도(음력 명절)
SEASONS = [
    dict(id="chuseok", name="추석", dates=[("2026-09-24", "2026-09-26"), ("2027-09-14", "2027-09-16"), ("2028-10-02", "2028-10-04")],
         item="songpyeon", greet="한가위만 같아라! 송편 빚는 {name} ◈ (상점에 송편 입고)",
         deco=[r" .-. ", r"(   )", r" '-' "], lines=["추석이에요! 송편은 반달 모양으로 빚어야 해요", "보름달한테 '빌드 성공'을 빌었어요",
                                                    "명절에도 AI를 부리다니… 대단해요"]),
    dict(id="seollal", name="설날", dates=[("2027-02-06", "2027-02-09"), ("2028-01-25", "2028-01-27")],
         item="tteokguk", greet="새해 복 많이 받으세요! 세배하는 {name} ◈ (상점에 떡국 입고)",
         deco=[r" [福] "], lines=["새해 복 많이 받으세요! 세뱃돈은 골드로 주세요", "떡국 먹고 한 살 더 먹었어요 (Lv은 그대로)"]),
    dict(id="xmas", name="크리스마스", dates=[("12-24", "12-25")], item="xmascake",
         greet="메리 크리스마스! 산타 모자 쓴 {name} ◈", deco=["  *  ", " /_\\ ", "/___\\"],
         lines=["메리 크리스마스! 선물은 머지된 PR이면 좋겠어요", "산타도 배포는 안 한대요"]),
    dict(id="halloween", name="할로윈", dates=[("10-31", "10-31")], item="candy",
         greet="Trick or Treat! 호박 쓴 {name} ◈", deco=[r"(^v^)"], lines=["사탕 안 주면 레거시 코드 보여줄 거예요!"]),
    dict(id="pepero", name="빼빼로데이", dates=[("11-11", "11-11")], item="pepero",
         greet="11/11 빼빼로데이! 1111은 이진수로 15예요 ◈", deco=[r"|||| "], lines=["1, 1, 1, 1… 이건 이진수 15예요"]),
    dict(id="devday", name="프로그래머의 날", dates=[("09-13", "09-13")], item=None,
         greet="오늘은 프로그래머의 날 (1년의 256번째 날)! 수고 많으세요 ◈", deco=[r"<256>"],
         lines=["2의 8제곱 날이에요! 오늘은 버그도 쉬었으면…"]),
    dict(id="aprilfool", name="만우절", dates=[("04-01", "04-01")], item=None,
         greet="만우절! 오늘 {name}의 말은 반쯤 거짓말이에요", deco=[r" ?!? "], lines=["저 사실 GPT예요 (거짓말)", "배포 금요일에 해도 돼요 (거짓말)"]),
    dict(id="hangul", name="한글날", dates=[("10-09", "10-09")], item=None,
         greet="한글날! 변수명은 영어로, 주석은 정성껏 ◈", deco=[r"[ㄱㄴ]"], lines=["한글 변수명은… 참아주세요"]),
]


# ============================================================== 집에서 생기는 소소한 일
# (문구, 효과) — 효과 키는 던전 이벤트와 같음
HOME_EVENTS = [
    ("택배가 도착했다! 뜯어보니…", {"items": 1}),
    ("옆자리 동료가 간식을 놓고 갔다", {"item": "samgak"}),
    ("사내 카페 쿠폰을 주웠다", {"item": "coffee"}),
    ("회사 굿즈 상자가 도착했다. 안에 골드가…?", {"gold": 50}),
    ("창밖에 무지개가 떴다", {"mood": 10}),
    ("누가 모니터에 포스트잇을 붙였다: '힘내요!'", {"mood": 8}),
    ("모니터가 절전 모드로 들어가 깜짝 놀랐다", {"energy": -4, "mood": -2}),
    ("화분에 새 잎이 났다", {"mood": 6}),
    ("PR이 승인됐다는 알림이 왔다 (누구 PR인지는 모름)", {"exp": 20}),
    ("의자 밑에서 동전을 주웠다", {"gold": 25}),
    ("사내 메신저에 '점심 뭐 먹지?'가 올라왔다", {"full": -3, "mood": 3}),
    ("누가 러버덕을 두고 갔다. 꽥.", {"mood": 5}),
]


# ============================================================== 메인 스토리 (v4)
# 시즌 1 「초록불을 찾아서」: 챕터 12개 = 지역 12개. 챕터 n 이 열려야 지역 n 에 들어갈 수 있다.
#   - 앞의 fast 개 챕터는 바로 열린다 (첫 주: 진행만 하면 다음 챕터)
#   - 그다음부터는 스토리 시작일 기준 every 일마다 하나씩 열린다 (그리고 앞 챕터를 끝내야 시작)
#   - 챕터 = 프롤로그(대화) → 미션(필수 3 + 보너스 1) → 챕터 보스(대화 + 전투) → 에필로그 + 보상
# 대사: (말하는 이, 문장). 말하는 이: NPCS 의 키 / "pet"(내 펫) / "boss"(챕터 보스) / "narr"(해설). {name} = 펫 이름
STORY = dict(season=1, title="초록불을 찾아서", en="THE LAST GREEN BUILD", fast=4, every=7,
             boss_energy=10, boss_full=4)

NPCS = {
    "owl": dict(name="시니어 부엉이", color="#75A1C7", art=[r"  ,___,  ", r"  {O,o}  ", r"  /)__)  ", r'   " "   ']),
    "duck": dict(name="러버덕", color="#C0E79D", art=[r"   __    ", r" <(o )__ ", r"  (  ._> ", r"   `---' "]),
    "ci": dict(name="CI 봇", color="#D4D6D8", art=[r"  [===]  ", r"  [o_o]  ", r"  /|CI|\ ", r"   | |   "]),
    "pm": dict(name="PM 고양이", color="#B8CEE0", art=[r"  /\_/\  ", r" ( ^.^ ) ", r"  > PM < ", r"         "]),
    "wolf": dict(name="온콜 늑대", color="#A5AAAE", art=[r"  /\  /\ ", r" ( -  - )", r"  \ zz / ", r"   \__/  "]),
    "lich": dict(name="레거시 리치", color="#81888D", art=[r"  ____   ", r" (x_x)   ", r"/|COBOL|\ ", r"  ||||   "]),
    "debt": dict(name="기술 부채", color="#F2F2F3", art=[r"\|/ ___ \|/", r"( TODO!! ) ", r"/|$$$$$$|\ ", r" /  ||  \  "]),
}

# 스탯 미션 문구 ({n} = 목표치)
STORY_STAT_TEXT = {
    "quests": "opencode 응답 {n}번 받기", "tools": "opencode 도구 {n}번 쓰기", "tokens": "토큰 {n}개 먹기",
    "cleaned": "버그 {n}마리 청소", "meals": "밥 {n}번 주기", "games": "미니게임 {n}판", "pats": "쓰다듬기 {n}번",
    "crafts": "공방에서 {n}번 제작", "raids": "주간 레이드 {n}번 출격", "todos_done": "opencode 할 일 {n}개 완료",
    "todo_lists": "할 일 목록 {n}개 끝까지 완료", "allies": "서브에이전트 동료 {n}번 합류",
    "compose": "컴포즈로 {n}번 보내기", "perm_fast": "허락 요청에 1분 안에 응답 {n}번",
}


def _mi(k, n=0, z=None, s=None, opt=False):
    return dict(k=k, n=n, z=z, s=s, opt=opt)


CHAPTERS = [
    dict(id="c01", title="월요일의 빨간불", en="RED MONDAY", zone="z1",
         summary="세상의 모든 빌드가 빨갛게 물들었다. 첫 번째 커밋 조각은 로컬호스트 평원에.",
         teaser="첫 조각을 찾아 로컬호스트 평원으로.",
         intro=[("narr", "어느 월요일 아침. 세상의 모든 빌드가 동시에 빨갛게 물들었다."),
                ("ci", "BUILD #4096 … FAILED ×   BUILD #4097 … FAILED ×   BUILD #4098 …"),
                ("owl", "허허, 결국 이날이 왔구먼. 초록불이 꺼졌어."),
                ("pet", "초록불이요? 그게 꺼지면 어떻게 되는데요?"),
                ("owl", "배포가 멈추고, 테스트가 울고, 개발자들이 퇴근을 못 하지."),
                ("owl", "전설에 따르면 '마지막 초록 빌드'는 커밋 조각 열두 개로 쪼개져 흩어졌다네."),
                ("owl", "첫 조각은 로컬호스트 평원에 있을 걸세. …로컬에선 늘 잘 됐으니까."),
                ("duck", "꽥."),
                ("owl", "이 오리를 데려가게. 말은 없지만, 들어는 준다네.")],
         boss=dict(mid="sb01", lvl=11,
                   intro=[("boss", "빌드… 실패… 빌드… 실패…"), ("pet", "말이 통하는 상대가 아니야!"), ("duck", "꽥!")],
                   mid_line="재시도… 재시도… 재시도…"),
         outro=[("narr", "슬라임이 터지자, 작은 초록 불빛이 떠올랐다."),
                ("ci", "커밋 조각 #1 … 확인. 해시 4f2a9c1."),
                ("owl", "잘했네. 그런데 슬라임 속에 이상한 주석이 있었지?"),
                ("narr", "// TODO: 나중에 고치기 (2019)"),
                ("owl", "…설마. 아니겠지. 다음 조각은 node_modules 심연이야.")],
         notes=["풀숲에서 누군가 쓰다 만 README를 주웠다. '설치 방법: 알아서'",
                "멀리서 CI 봇의 목소리가 들린다. 'FAILED… FAILED…'"],
         missions=[_mi("floor", 5, z="z1"), _mi("stat", 5, s="quests"), _mi("stat", 3, s="cleaned"),
                   _mi("stat", 3, s="todos_done", opt=True)],
         reward=dict(gold=300, items={"coffee": 3}, exp=0.5), bonus=dict(gold=100, items={"hotfixpatch": 1}),
         hash="4f2a9c1"),
    dict(id="c02", title="끝없는 의존성", en="DEPENDENCY HELL", zone="z2",
         summary="누군가 패키지를 지워 버렸다. 심연 아래에서 수상한 서명이 발견된다.",
         teaser="사라진 패키지를 쫓아 node_modules 심연으로.",
         intro=[("narr", "node_modules 심연. 끝까지 내려가는 데만 사흘이 걸린다는 깊은 바다."),
                ("owl", "여기선 조심하게. 패키지 하나를 지우면 다른 데서 두 개가 자라거든."),
                ("pet", "조각 신호가… 아래쪽에서 느껴져요!"),
                ("narr", "저 깊은 곳에서 package-lock.json 타는 냄새가 올라왔다."),
                ("duck", "꽥? (불안)")],
         boss=dict(mid="sb02", lvl=18,
                   intro=[("boss", "이 패키지는 내 거야! npm unpublish!"), ("pet", "그걸 지우면 세상 빌드가 다 깨진다고!"),
                          ("boss", "알 게 뭐람~ 나중에 누가 고치겠지~")],
                   mid_line="버전을 올려 주마! 메이저로! 호환성 따윈 없다!"),
         outro=[("narr", "너구리가 도망치며 쪽지 한 장을 떨어뜨렸다."),
                ("narr", "'위임장 — 모든 수정은 나중에 할 것. 서명: 기술 부채'"),
                ("owl", "기술 부채… 그 이름을 여기서 보게 될 줄이야."),
                ("ci", "커밋 조각 #2 … 확인. 해시 9b7e0d4.")],
         notes=["peerDependency 경고문이 벽을 뒤덮고 있다. 아무도 읽지 않는다.",
                "바닥에 'npm install --force'라고 적힌 부적이 떨어져 있다."],
         missions=[_mi("floor", 10, z="z2"), _mi("stat", 30, s="tools"), _mi("stat", 5, s="pats"),
                   _mi("stat", 2, s="allies", opt=True)],
         reward=dict(gold=500, items={"hotfixpatch": 2}, exp=0.5), bonus=dict(gold=150, items={"cacheflush": 2}),
         hash="9b7e0d4"),
    dict(id="c03", title="무덤 속의 결제 시스템", en="THE PAYMENT CRYPT", zone="z3",
         summary="1987년부터 결제를 지켜 온 리치. 그가 '나중에'의 사내를 기억한다.",
         teaser="무덤 깊은 곳, 1987년의 결제 시스템을 찾아서.",
         intro=[("narr", "레거시 코드 무덤. 2003년의 코드가 아직도 결제를 처리하고 있다."),
                ("owl", "여긴 오래된 친구가 잠들어 있네. 1987년부터 결제를 지켜 온 리치지."),
                ("lich", "…누가… 내 COBOL을… 건드리는가…"),
                ("pet", "건드리려는 게 아니에요! 커밋 조각을 찾고 있어요."),
                ("lich", "조각이라… 그자도 그걸 찾으러 왔었지. '나중에'를 입에 달고 다니던 자.")],
         boss=dict(mid="sb03", lvl=25,
                   intro=[("boss", "나는 2011년에 시작된 마이그레이션… 진행률… 67%…"), ("pet", "12년 동안 67%라고?!"),
                          ("lich", "저것을 끝내 주게. 나도 이제 좀 쉬고 싶네.")],
                   mid_line="롤백… 롤백한다… 다시 1%부터…"),
         outro=[("narr", "진행률이 마침내 100%에 닿았다. 무덤에 햇살이 들었다."),
                ("lich", "고맙네. 그자는 서버실로 갔네. 조심하게… 그는 모든 걸 미루게 만들지."),
                ("ci", "커밋 조각 #3 … 확인. 해시 1c0de42."),
                ("owl", "이제부터가 진짜 모험이네. 다음 조각의 신호는 곧 잡힐 거야.")],
         notes=["묘비명: '여기 전역 변수 잠들다. 누구나 나를 바꿀 수 있었다.'",
                "누군가 남긴 주석: '이 줄을 지우면 결제가 멈춤. 이유는 모름.'"],
         missions=[_mi("clear", z="z3"), _mi("stat", 25, s="quests"), _mi("stat", 2, s="games"),
                   _mi("stat", 10, s="todos_done", opt=True)],
         reward=dict(gold=800, items={"exp_boost": 1}, exp=0.5, ach="story_ch3"), bonus=dict(gold=250, items={"boss_core": 1}),
         hash="1c0de42"),
    dict(id="c04", title="새벽 3시의 서버실", en="3 AM PAGER", zone="z4",
         summary="매일 새벽 3시, 서버실에서 누군가 모든 걸 '나중에'로 미룬다.",
         teaser="새벽 3시의 알림을 쫓아 프로덕션 서버실로.",
         intro=[("narr", "서버실에서 새벽마다 알림이 울린다는 소문이 들려왔다."),
                ("wolf", "난 온콜 늑대. 사흘째 못 잤어. …아우우우 (하품)"),
                ("wolf", "누가 서버실에 크론잡을 심어 놨어. 매일 새벽 3시에 뭔가를 '나중에'로 미뤄."),
                ("pet", "기술 부채의 짓이에요!"),
                ("duck", "꽥!! (단호)")],
         boss=dict(mid="sb04", lvl=31,
                   intro=[("boss", "0 3 * * * … 0 3 * * * …"), ("wolf", "저 녀석이야! 매일 새벽 3시에 날 깨우는 놈!"),
                          ("pet", "오늘 밤은 푹 자게 해 줄게요!")],
                   mid_line="재시도 간격을 1초로 줄인다! 알림 폭탄이다!"),
         outro=[("wolf", "조용하다… 이게 얼마 만의 정적이야."),
                ("wolf", "고마워. 대신 알려 줄게. 그자는 회의실 미궁으로 숨었어. 거긴 들어가면 못 나와."),
                ("ci", "커밋 조각 #4 … 확인. 해시 0ff1ce3.")],
         notes=["랙 사이에 '건드리지 마세요 — 운영팀' 쪽지가 붙어 있다.",
                "온콜 늑대의 발자국이 커피 자판기 앞에서 끝난다."],
         missions=[_mi("clear", z="z4"), _mi("kills", 40, z="z4"), _mi("stat", 8, s="cleaned"),
                   _mi("stat", 3, s="perm_fast", opt=True)],
         reward=dict(gold=1200, items={"vacation": 1, "boss_core": 2}, exp=0.5), bonus=dict(gold=350, items={"boss_core": 1}),
         hash="0ff1ce3"),
    dict(id="c05", title="끝나지 않는 회의", en="THE ENDLESS MEETING", zone="z5",
         summary="회의실 미궁의 PM 고양이. 안건은 늘어나고, 시간은 사라진다.",
         teaser="끝나지 않는 회의를 끝내러 회의실 미궁으로.",
         intro=[("narr", "회의실 미궁. 들어가면 1시간, 나오면 3시간이 지나 있는 곳."),
                ("pm", "어머, 딱 좋은 타이밍! 이것도 같이 해 주실 수 있죠? 금방이에요~"),
                ("pet", "저는 조각 찾으러 온 건데요…"),
                ("pm", "그럼 조각 찾으면서 이것도, 저것도, 요것도요~"),
                ("owl", "(속삭이며) 거절하는 것도 기술이라네.")],
         boss=dict(mid="sb05", lvl=44,
                   intro=[("boss", "자, 남은 안건은 47개입니다. 다음 안건은 '회의를 줄이는 방법'에 대한 회의입니다."),
                          ("pm", "앗, 이 회의… 제가 잡은 거였나…?"), ("pet", "이 회의, 제가 끝내겠습니다!")],
                   mid_line="잠깐, 이 건은 따로 회의를 잡읍시다. 지금 당장."),
         outro=[("narr", "주재자는 쓰러지면서도 외쳤다. '…이 건은 다음 회의에서…'"),
                ("pm", "헉, 오늘 처음으로 회의가 일찍 끝났어요! 감동…"),
                ("pm", "그분(?)은 구름 위로 올라갔어요. 클라우드 요금으로 세상을 덮겠대요."),
                ("ci", "커밋 조각 #5 … 확인. 해시 5ca1ab1.")],
         notes=["화이트보드에 '다음 주까지'라고 적혀 있다. 날짜는 2년 전이다.",
                "빈 회의실에서 누군가 혼자 '음소거 해제하셨어요?'라고 말하고 있다."],
         missions=[_mi("clear", z="z5"), _mi("stat", 50, s="quests"), _mi("stat", 4, s="games"),
                   _mi("stat", 3, s="compose", opt=True)],
         reward=dict(gold=1600, items={"duck_charm": 1}, mats={"legacy_scroll": 2}, exp=0.5),
         bonus=dict(gold=500, items={"boss_core": 1}), hash="5ca1ab1"),
    dict(id="c06", title="구름 위의 청구서", en="BILLING IN THE CLOUDS", zone="z6",
         summary="429 드래곤 로드, 그리고 처음 모습을 드러낸 기술 부채.",
         teaser="빨간불의 배후가 기다리는 클라우드 성층권으로.",
         intro=[("narr", "클라우드 성층권. 구름 위의 서버들이 요금처럼 불어나는 곳."),
                ("owl", "여기부터는 나도 가 본 적이 없네. …아니, 한 번 와 봤지. 아주 오래전에."),
                ("pet", "선배님, 뭔가 숨기는 거 있죠?"),
                ("owl", "…조각을 다 모으면 말해 주겠네."),
                ("narr", "구름 사이로 거대한 그림자가 지나갔다. 429, 429, 429…")],
         boss=dict(mid="sb06", lvl=56,
                   intro=[("boss", "요청이 너무 많다. 잠시 후 다시 시도하라. Retry-After: 영원."),
                          ("debt", "(구름 너머에서) 후후… 나중에, 나중에 다시 오렴."), ("pet", "누구야?!")],
                   mid_line="지수 백오프다! 1초, 2초, 4초, 8초…!"),
         outro=[("narr", "드래곤이 쓰러지자 구름이 갈라지고, 그가 모습을 드러냈다."),
                ("debt", "반갑구나, 작은 토큰. 나는 기술 부채. 너희가 미뤄 둔 모든 것이지."),
                ("debt", "조각을 모아 봤자 소용없다. 빌드는 언젠가 또 깨진다. 나중에… 언젠가…"),
                ("narr", "그는 남은 커밋 조각들을 멀리 흩뿌리고 사라졌다. 아무도 가 본 적 없는 곳으로."),
                ("ci", "커밋 조각 #6 … 확인. 해시 c10dd06. 남은 조각: 6."),
                ("owl", "…그래. 이제 말할 때가 됐군. 저 녀석이 처음 생긴 날에 대해.")],
         notes=["구름 속에서 '예상 청구액'이 번쩍인다. 못 본 걸로 했다.",
                "누군가 켜 두고 잊어버린 GPU 인스턴스가 조용히 돌고 있다."],
         missions=[_mi("clear", z="z6"), _mi("stat", 300, s="tools"), _mi("stat", 5, s="games"),
                   _mi("stat", 3_000_000, s="tokens", opt=True)],
         reward=dict(gold=2000, gear=["owl_feather"], exp=0.5, ach="story_ch6"), bonus=dict(gold=600, items={"boss_core": 2}),
         hash="c10dd06"),
    dict(id="c07", title="야근의 탑", en="TOWER OF OVERTIME", zone="z7",
         summary="2019년 금요일 오후 5시 58분. 첫 번째 TODO가 적힌 곳.",
         teaser="첫 번째 TODO가 적힌 곳, 야근의 탑으로.",
         intro=[("owl", "2019년 어느 금요일 오후. 한 개발자가 급한 버그를 막고 이렇게 적었지."),
                ("owl", "'TODO: 나중에 고치기.' …그 한 줄이 모든 것의 시작이었네."),
                ("pet", "그 개발자가 누군데요?"),
                ("owl", "…탑 꼭대기에서 알려 주지. 야근의 탑은 올라갈수록 퇴근이 멀어지네."),
                ("duck", "꽥…")],
         boss=dict(mid="sb07", lvl=68,
                   intro=[("boss", "이번 주만. 이번 주만 고생하면 돼. …라고 한 지 3년째다."),
                          ("pet", "야근은 끝나야 해! 퇴근은 권리야!"), ("duck", "꽥꽥! (동의)")],
                   mid_line="주말도 반납이다! 크런치 모드 가동!"),
         outro=[("narr", "거인이 무너지자 탑 꼭대기의 낡은 모니터가 켜졌다."),
                ("ci", "$ git log --reverse | head -1"),
                ("narr", "'TODO: 나중에 고치기' — author: owl, 2019-03-15 17:58 (금)"),
                ("pet", "선배님…?!"),
                ("owl", "…그래. 그 주석, 내가 쓴 걸세. 금요일 오후 5시 58분이었지."),
                ("ci", "커밋 조각 #7 … 확인. 해시 7e11ab5.")],
         notes=["계단마다 빈 에너지드링크 캔이 쌓여 있다.", "벽의 달력이 금요일에서 멈춰 있다. 몇 년째인지는 모른다."],
         missions=[_mi("clear", z="z7"), _mi("kills", 80, z="z7"), _mi("stat", 6, s="games"),
                   _mi("stat", 30, s="todos_done", opt=True)],
         reward=dict(gold=2500, gear=["hood_gore"], exp=0.5), bonus=dict(gold=750, items={"boss_core": 2}),
         hash="7e11ab5"),
    dict(id="c08", title="마이그레이션 사막", en="MIGRATION DESERT", zone="z8",
         summary="월요일에 고치려던 버그는 5년이 흘러 괴물이 됐다.",
         teaser="스키마가 모래처럼 흘러내리는 마이그레이션 사막으로.",
         intro=[("owl", "나는 그 버그를 월요일에 고칠 생각이었네. 그런데 월요일엔 급한 일이 생겼지."),
                ("owl", "화요일에도, 수요일에도. 그렇게 5년이 흘렀어. 그사이 TODO가 자라서… 저것이 됐네."),
                ("pet", "선배님 탓만은 아니에요. 다들 '나중에'라고 하잖아요."),
                ("owl", "고맙네. …사막 너머에 조각이 있어. 스키마가 모래처럼 흘러내리는 곳이지.")],
         boss=dict(mid="sb08", lvl=78,
                   intro=[("boss", "수수께끼를 풀어라. 아침엔 네 발, 점심엔 두 발, 저녁엔 롤백하는 것은?"),
                          ("pet", "…금요일 배포요?"), ("boss", "…정답이다. 하지만 싸움은 피할 수 없다!")],
                   mid_line="503! 점검 중이다! 공격을 받지 않는다! …거짓말이다."),
         outro=[("boss", "훌륭하다. 롤백할 줄 아는 자만이 사막을 건널 수 있다."),
                ("ci", "커밋 조각 #8 … 확인. 해시 d0e5a07."),
                ("narr", "사막 끝, 성벽처럼 높은 방화벽이 보였다.")],
         notes=["모래 속에서 'ALTER TABLE'이 반쯤 묻힌 채 멈춰 있다.", "신기루 속에서 NULL과 빈 문자열이 싸우고 있다."],
         missions=[_mi("clear", z="z8"), _mi("enh", 6), _mi("stat", 20, s="cleaned"),
                   _mi("stat", 3, s="todo_lists", opt=True)],
         reward=dict(gold=3000, gear=["kb_ergodox"], exp=0.5), bonus=dict(gold=900, mats={"legacy_scroll": 2}),
         hash="d0e5a07"),
    dict(id="c09", title="보안 감사 요새", en="THE AUDIT FORTRESS", zone="z9",
         summary="하드코딩된 비밀번호 37개. 그리고 아무도 모르는 구멍.",
         teaser="비밀번호 37개가 숨겨진 보안 감사 요새로.",
         intro=[("narr", "보안 감사 요새. 모든 요청이 세 번씩 검사받는 곳."),
                ("ci", "경고: 이 구역에서 하드코딩된 비밀번호 37개가 발견되었습니다."),
                ("pet", "37개나?! 누가 이렇게…"),
                ("owl", "급하면 다들 그러지. '나중에 환경 변수로 옮기자'면서."),
                ("duck", "꽥. (한숨)")],
         boss=dict(mid="sb09", lvl=88,
                   intro=[("boss", "나는 아무도 모르는 구멍. 패치 노트에 없는 존재."),
                          ("pet", "이제 알았으니까 패치할 거야!"), ("owl", "CVE 번호는 우리가 붙여 주지!")],
                   mid_line="권한 상승! 이제 나는 root다!"),
         outro=[("narr", "가고일이 돌로 굳었다. 요새의 경보가 하나씩 꺼졌다."),
                ("ci", "커밋 조각 #9 … 확인. 해시 5ec0de9. 남은 조각: 3."),
                ("debt", "(어딘가에서) 후후… 여기까지 오다니. 다음은 네 머릿속이다.")],
         notes=["성벽에 붙은 포스트잇: 'admin / admin123'. 떼어 버렸다.",
                "만료된 인증서들이 줄지어 행진한다. 'NET::ERR_CERT_DATE_INVALID'"],
         missions=[_mi("clear", z="z9"), _mi("stat", 100, s="quests"), _mi("stat", 15, s="pats"),
                   _mi("stat", 2, s="raids", opt=True)],
         reward=dict(gold=3500, gear=["lich_ring"], exp=0.5, ach="story_ch9"), bonus=dict(gold=1000, items={"boss_core": 2}),
         hash="5ec0de9"),
    dict(id="c10", title="할루시네이션 늪", en="HALLUCINATION MIRE", zone="z10",
         summary="그럴듯한 답이 가장 위험하다. 문서에 없는 함수의 늪.",
         teaser="문서에 없는 함수가 사는 할루시네이션 늪으로.",
         intro=[("narr", "할루시네이션 늪. 자신만만한 목소리가 존재하지 않는 API를 알려 주는 곳."),
                ("pet", "여기… 뭔가 이상해요. 문서에 없는 함수가 보여요."),
                ("owl", "그럴듯한 건 다 의심하게. 확신에 찬 건 더더욱."),
                ("debt", "(늪 속에서) 걱정 마, 그 함수는 존재해. 나중에 누가 만들겠지."),
                ("duck", "꽥!! (경고)")],
         boss=dict(mid="sb10", lvl=96,
                   intro=[("boss", "나는 모든 대화를 삼킨다. 네 첫 번째 지시는 이미 잊었다."),
                          ("pet", "그럼 요약해 줄게! 꺼억 말고, 제대로!"),
                          ("narr", "{name}은(는) 지금까지의 모험을 세 줄로 요약해 외쳤다.")],
                   mid_line="컨텍스트가 넘친다! 앞부분을 잘라 낸다!"),
         outro=[("narr", "리바이어던이 압축되어 작은 조개가 되었다."),
                ("ci", "커밋 조각 #10 … 확인. 해시 a11ce10."),
                ("owl", "두 개 남았네. 저 협곡을 지나면… 메인 브랜치야.")],
         notes=["표지판: '이 길은 100% 정확합니다 (출처: 이 표지판)'", "늪 위에 논문 인용 [1][2][3]이 떠다닌다. 전부 존재하지 않는다."],
         missions=[_mi("clear", z="z10"), _mi("kills", 120, z="z10"), _mi("stat", 8, s="games"),
                   _mi("stat", 5, s="compose", opt=True)],
         reward=dict(gold=4000, gear=["suit_oncall"], exp=0.5), bonus=dict(gold=1200, items={"boss_core": 2}),
         hash="a11ce10"),
    dict(id="c11", title="모노레포 대협곡", en="MONOREPO CANYON", zone="z11",
         summary="빌드 47분, 대기열 143번째. 옛 친구들이 모인다.",
         teaser="빌드 47분의 모노레포 대협곡으로.",
         intro=[("narr", "모노레포 대협곡. 한 저장소에 백 개의 서비스가 사는 거대한 협곡."),
                ("ci", "알림: 이 협곡의 빌드는 평균 47분 걸립니다."),
                ("pet", "47분이요?! 그동안 뭐 해요?"),
                ("owl", "커피를 마시지. 그리고 기도하지."),
                ("lich", "도우러 왔네. 1987년부터 배치 작업을 기다려 온 몸이니, 기다림엔 자신 있지."),
                ("wolf", "나도 왔어. 오늘은 온콜 아니거든. …아마도.")],
         boss=dict(mid="sb11", lvl=104,
                   intro=[("boss", "줄을 서시오. 당신의 PR은 대기열 143번째입니다."),
                          ("pet", "새치기는 안 해! 정면 돌파다!"), ("lich", "충돌은 내가 막지. 리베이스는 옛날부터 내 특기였네.")],
                   mid_line="대기열 재정렬! 당신의 PR은 이제 287번째!"),
         outro=[("narr", "머지 큐가 텅 비었다. 협곡에 초록 불빛이 번지기 시작했다."),
                ("ci", "커밋 조각 #11 … 확인. 해시 3a9e011. 남은 조각: 1."),
                ("owl", "이제 마지막이야. 메인 브랜치로 가세. 그가 기다리고 있어.")],
         notes=["협곡 벽에 새겨진 CODEOWNERS. 모든 줄에 퇴사한 사람 이름뿐이다.", "빌드 캐시가 '미스'라고 울며 날아다닌다."],
         missions=[_mi("clear", z="z11"), _mi("stat", 3, s="crafts"), _mi("stat", 800, s="tools"),
                   _mi("stat", 15, s="allies", opt=True)],
         reward=dict(gold=4500, gear=["kb_optical"], exp=0.5), bonus=dict(gold=1400, mats={"legacy_scroll": 3}),
         hash="3a9e011"),
    dict(id="c12", title="메인 브랜치", en="MAIN BRANCH", zone="z12",
         summary="모든 커밋이 흘러드는 곳. 마지막 조각은 그의 안에 있다.",
         teaser="모든 커밋이 흘러드는 메인 브랜치로. 마지막 조각을 찾아서.",
         intro=[("narr", "메인 브랜치. 모든 커밋이 흘러드는 곳. 성벽에는 수만 개의 TODO가 새겨져 있다."),
                ("debt", "드디어 왔구나. 열한 개의 조각이라… 하지만 마지막 하나는 내 안에 있다."),
                ("debt", "나를 없앨 수 있을 것 같나? 나는 너희가 미룬 모든 것. 너희가 있는 한, 나도 있다."),
                ("owl", "없애러 온 게 아니네. …갚으러 왔지."),
                ("pet", "선배님, 같이 가요. 덕도, 리치도, 늑대도, 모두 같이!"),
                ("duck", "꽥!!!")],
         boss=dict(mid="sb12", lvl=112, phase2=0.5,
                   intro=[("boss", "복리의 공포를 보여 주마! 이자가 이자를 낳는다!"),
                          ("pet", "한 번에 다 못 갚아도 괜찮아. 조금씩, 매일 갚을 거야!")],
                   mid_line="나중에… 나중에 하자… 다음 스프린트에…",
                   phase2_lines=[("boss", "리파이낸싱! 만기를 연장한다!"), ("owl", "지금이야, {name}! 리팩터링!")]),
         outro=[("narr", "대마왕의 몸에서 마지막 커밋 조각이 떨어져 나왔다."),
                ("ci", "커밋 조각 #12 … 확인. 해시 9ee7012."),
                ("ci", "조각 12/12 병합 중 … … …  BUILD #4096 … PASSED √"),
                ("narr", "세상의 모든 빌드가 초록빛으로 물들었다."),
                ("debt", "(작아진 채로) …나는 사라지지 않는다. 너희가 코드를 짜는 한."),
                ("owl", "알고 있네. 그러니 매주 조금씩 갚겠네. 주간 레이드처럼 말이야."),
                ("debt", "…그 정도면… 봐 주지. (이자가 조금 줄었다)"),
                ("duck", "…고마워, {name}. 네가 설명해 준 덕분에, 전부 들을 수 있었어."),
                ("pet", "덕이… 말을 했다?!"),
                ("duck", "꽥."),
                ("narr", "TOKEN QUEST 시즌 1 — 「초록불을 찾아서」 끝."),
                ("narr", "빌드는 언젠가 또 깨질 것이다. 그때 다시 만나자.")],
         notes=["성벽의 TODO 하나를 지웠다. 조금… 가벼워진 느낌이다.", "'git push --force'라고 적힌 깃발이 부러져 있다."],
         missions=[_mi("clear", z="z12"), _mi("kills", 150, z="z12"), _mi("stat", 150, s="quests"),
                   _mi("stat", 10_000_000, s="tokens", opt=True)],
         reward=dict(gold=8000, gear=["kb_green", "green_badge"], decos=["greenlight"], exp=1.0, ach="season1"),
         bonus=dict(gold=2500, gear=["robe_senior"]), hash="9ee7012"),
]
